### ISSUE TITLE
Crash when run this example

### ISSUE THREAD

**Issue by zj8331182** [google/flutter-desktop-embedding#576] opened 2019-09-26 03:21 UTC
**Describe the bug**
I had run this example success on the old version of flutter , but I run flutter upgrade today.
When I run this example on my windows computer, I get a error on the console

```
[  +19 ms] executing: build\windows\x64\Debug\Runner\Flutter Desktop Example.exe
[ +180 ms] [ERROR:c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc(629)] Not running in AOT mode but could not resolve the kernel binary.
[   +2 ms] [ERROR:c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc(53)] Returning error 'kInvalidArguments' (2) from Flutter Embedder API call to 'FlutterEngineRun'. Origin: c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc:631
[        ] Failed to start Flutter engine: error 2
[        ] Failed to create view.
```

The window no show anything and crash.

**Doctor Output**
Please provide the output of `flutter doctor -v`:
```
[√] Flutter (Channel master, v1.10.7-pre.19, on Microsoft Windows [Version 10.0.18362.295], locale zh-CN)
    • Flutter version 1.10.7-pre.19 at D:\flutter_sdk\flutter
    • Framework revision 5caad71f1d (89 minutes ago), 2019-09-25 21:49:41 -0400
    • Engine revision 739ee77864
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 6c81690c3a)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\software\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.2.29306.81

[√] Android Studio (version 3.5)
    • Android Studio at D:\software\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18362.295]

• No issues found!

```

**Comment by stuartmorgan** [comment] 2019-09-26 03:58
> I run flutter upgrade today

Did you upgrade flutter-desktop-embedding at the same time, per this project's instructions? I.e., are you at `4e25c5bee2f0ddb4b9cbaf58ad7d2e05eced6c95`?

**Comment by zj8331182** [comment] 2019-09-26 07:35
I had change some code myself so I not upgrade this repo,so I need keep this repo in latest?

**Comment by zj8331182** [comment] 2019-09-26 08:01
I has upgrade this repo to  4e25c5bee2f0ddb4b9cbaf58ad7d2e05eced6c95 but not work. If I switch flutter sdk repo to tag 1.10.6,it work well

**Comment by by90** [comment] 2019-09-26 08:24
> > I run flutter upgrade today
> 
> Did you upgrade flutter-desktop-embedding at the same time, per this project's instructions? I.e., are you at `4e25c5bee2f0ddb4b9cbaf58ad7d2e05eced6c95`?

I have same program...even I upgrade flutter-desktop-embedding use git pull. it can't run,after I upgrade flutter.

**Comment by by90** [comment] 2019-09-26 09:14
after such oprations:
flutter channel master
flutter upgrade
flutter doctor
cd \flutter-desktop-embedding
git pull

and then flutter run -d windows -v
here is the log information:
PS C:\flutter-desktop-embedding\example> flutter run -d windows -v
[  +25 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +107 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 5caad71f1dce1db0e629dfbe1b33c9bddb3b602b
[   +1 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +135 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.10.6-19-g5caad71f1
[  +10 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +85 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +3 ms] executing: [C:\flutter\] git ls-remote --get-url origin
[  +70 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +123 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +77 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +109 ms] executing: C:\Users\bdj\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +35 ms] Exit code 0 from: C:\Users\bdj\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[  +22 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +16 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +208 ms] Launching lib\main.dart on Windows in debug mode...
[  +32 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -requires
Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[  +42 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -requires
Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[   +2 ms] [
             {
               "instanceId": "7ece0e13",
               "installDate": "2019-04-25T00:28:30Z",
               "installationName": "VisualStudio/16.2.5+29306.81",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.2.29306.81",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "閫傜敤浜庡鐢熴€佸紑鏀炬簮浠ｇ爜鍜屼釜浣撳紑鍙戜汉鍛樼殑鍏嶈垂銆佸叏鍔熻兘鍨?IDE",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.2.5",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2019-09-16T01:11:21.2487988Z",
               "catalog": {
                 "buildBranch": "d16.2",
                 "buildVersion": "16.2.29306.81",
                 "id": "VisualStudio/16.2.5+29306.81",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.2.5",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "5",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.2.5+29306.81",
                 "requiredEngineVersion": "2.2.3074.64249"
               },
               "properties": {
                 "campaignId": "2093693436.1498604041",
                 "channelManifestId": "VisualStudio.16.Release/16.2.5+29306.81",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[  +26 ms] Building Windows application...
[ +442 ms] **********************************************************************
[   +2 ms] ** Visual Studio 2019 Developer Command Prompt v16.2.5
[   +2 ms] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[+3062 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[  +89 ms] 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.2.37902+b5aaefc9f
[   +3 ms] 版权所有(C) Microsoft Corporation。保留所有权利。
[   +3 ms] 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
[  +42 ms] 生成启动时间为 2019/9/26 17:10:47。
[ +163 ms] 节点 1 上的项目“C:\flutter-desktop-embedding\example\windows\Runner.sln”(默认目标)。
[   +3 ms] ValidateSolutionConfiguration:
[   +2 ms]   正在生成解决方案配置“Debug|x64”。
[ +173 ms] 项目“C:\flutter-desktop-embedding\example\windows\Runner.sln”(1)正在节点 1
上生成“C:\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj”(2) (默认目标)。
[   +6 ms] 项目“C:\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj”(2)正在节点 1
上生成“C:\flutter-desktop-embedding\example\windows\FlutterBuild.vcxproj”(3) (默认目标)。
[   +2 ms] InitializeBuildStatus:
[        ]   正在创建“x64\Debug\Flutter Build.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
[   +2 ms] CustomBuildStep:
[        ]   Running Flutter backend build
[   +5 ms]   "C:\flutter-desktop-embedding\example\windows\scripts\prepare_dependencies" Debug
[   +2 ms]   :VCEnd
[+4352 ms] FinalizeBuildStatus:
[   +2 ms]   正在删除文件“x64\Debug\Flutter Build.tlog\unsuccessfulbuild”。
[   +3 ms]   正在对“x64\Debug\Flutter Build.tlog\Flutter Build.lastbuildstate”执行 Touch 任务。
[        ] 已完成生成项目“C:\flutter-desktop-embedding\example\windows\FlutterBuild.vcxproj”(默认目标)的操作。
[  +60 ms] 项目“C:\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj”(2)正在节点 1
上生成“C:\flutter-desktop-embedding\example\windows\Runner.vcxproj”(4) (默认目标)。
[   +5 ms] InitializeBuildStatus:
[   +2 ms]
正在创建“C:\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild”，因为已指定
“AlwaysCreate”。
[  +54 ms] ClCompile:
[   +1 ms]   所有输出均为最新。
[  +20 ms] ResourceCompile:
[   +1 ms]   所有输出均为最新。
[   +5 ms] ManifestResourceCompile:
[   +1 ms]   所有输出均为最新。
[  +25 ms] Link:
[   +2 ms]   所有输出均为最新。
[   +3 ms]   Runner.vcxproj -> C:\flutter-desktop-embedding\example\windows\..\build\windows\x64\Debug\Runner\Flutter Desktop
Example.exe
[   +1 ms] CustomBuildStep:
[        ]   Bundling dependencies
[   +1 ms]   "C:\flutter-desktop-embedding\example\windows\scripts\bundle_assets_and_deps"
"C:\flutter-desktop-embedding\example\windows\flutter\ephemeral\"
"C:\flutter-desktop-embedding\example\windows\..\build\windows\x64\Debug\Runner\" "Flutter Desktop Example.exe"
[   +4 ms]   :VCEnd
[ +136 ms]   复制了 11 个文件
[  +30 ms]   复制了 0 个文件
[  +31 ms]   复制了 0 个文件
[  +11 ms] FinalizeBuildStatus:
[        ]
正在删除文件“C:\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild”。
[   +1 ms]
正在对“C:\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\Runner.lastbuildstate”执行
Touch 任务。
[   +1 ms] 已完成生成项目“C:\flutter-desktop-embedding\example\windows\Runner.vcxproj”(默认目标)的操作。
[        ] 已完成生成项目“C:\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj”(默认目标)的操作。
[        ] 已完成生成项目“C:\flutter-desktop-embedding\example\windows\Runner.sln”(默认目标)的操作。
[        ] 已成功生成。
[        ]     0 个警告
[   +1 ms]     0 个错误
[        ] 已用时间 00:00:05.13
[  +34 ms] Building Windows application... (completed in 8.8s)
[   +3 ms] executing: build\windows\x64\Debug\Runner\Flutter Desktop Example.exe
[  +47 ms] [ERROR:c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc(629)] Not running in AOT mode but could
not resolve the kernel binary.
[   +8 ms] [ERROR:c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc(53)] Returning error 'kInvalidArguments'
(2) from Flutter Embedder API call to 'FlutterEngineRun'. Origin:
c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc:631
[   +5 ms] Failed to start Flutter engine: error 2
[   +2 ms] Failed to create view.

**Comment by stuartmorgan** [comment] 2019-09-26 14:17
> so I need keep this repo in latest?

Yes, please see the README for this project. In this case that didn't end up being the issue, but in general updating Flutter without updating FDE is unsupported, and will regularly break.

Tracking in https://github.com/flutter/flutter/issues/41352 since it looks like a regression on the Flutter side at this point, so closing this as a duplicate.

**Closed by stuartmorgan** 2019-09-26 14:17 UTC
