### ISSUE TITLE
Example on Windows doesnt respond to mouse input

### ISSUE THREAD

**Issue by deanchalk** [google/flutter-desktop-embedding#363] opened 2019-05-01 06:21 UTC
When I run the example on Windows, I dont get any response from the mouse. However, there are errors in the terminal:

**C:\Projects\flutter-desktop-embedding\example>flutter run
Launching lib/main.dart on Windows in debug mode...
Building Windows application...
[ERROR:c:\b\s\w\ir\k\src\flutter\shell\platform\embedder\embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[ERROR:c:\b\s\w\ir\k\src\flutter\shell\platform\embedder\embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
Syncing files to device Windows...
 2,187ms (!)**

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:63634/vhLdJGirGUc=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

**Describe the bug**
Please provide a clear and concise description of the bug, including steps to reproduce, and, if relevant, screenshots.

**Development Environment (please complete the following information):**
* OS: 
* Developer tools version (Xcode, Visual Studio, or gcc): 

**Doctor Output**
For build issues, please provide the output of `flutter doctor -v`:
```
```

If the build is of anything other than `example`, please also provide the output of `tools/run_dart_tool doctor`:
```
```

**Comment by jonahwilliams** [comment] 2019-05-01 06:23
Duplicate of https://github.com/flutter/flutter/issues/31884

**Closed by jonahwilliams** 2019-05-01 06:23 UTC

**Comment by stuartmorgan** [comment] 2019-05-01 14:42
Those errors are longstanding (and should arguably be warnings) and are unrelated to the issue.
