### ISSUE TITLE
Typing in TextField lets app crash

### ISSUE THREAD

**Issue by jld3103** [google/flutter-desktop-embedding#450] opened 2019-07-08 08:45 UTC
**Describe the bug**
When I type in a ```TextField``` (only entering the ```TextField``` works), the app crashes with only this error message:
```
Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///tmp/exampleULBUSS/example/)
[   +3 ms] Sending to VM service: _deleteDevFS({fsName: example})
[ +256 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
```

**Development Environment (please complete the following information):**
* OS: Ubuntu 19.04
* Developer tools version (Xcode, Visual Studio, or gcc): gcc 8.3.0

**Doctor Output**
For build issues, please provide the output of `flutter doctor -v`:
```
[✓] Flutter (Channel master, v1.8.1-pre.23, on Linux, locale en_US.UTF-8)
    • Flutter version 1.8.1-pre.23 at /home/jld3103/flutter
    • Framework revision 3bf91b5436 (3 days ago), 2019-07-05 12:59:32 -0700
    • Engine revision 3c51a7bfff
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/jld3103/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /home/jld3103/android/sdk
    • Java binary at: /home/jld3103/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 8.0.0
    • GNU Make 4.2.1

[✓] Android Studio (version 3.2)
    • Android Studio at /home/jld3103/android-studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /home/jld3103/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/183.4284.148
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4733

[✓] VS Code (version 1.35.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • Linux  • Linux  • linux-x64      • Linux
    • Chrome • chrome • web-javascript • Google Chrome 75.0.3770.100 


• No issues found!
```

**Comment by moshTech** [comment] 2019-07-08 10:40
Am struggling with this also.

**Comment by stuartmorgan** [comment] 2019-07-08 12:37
Duplicate of #447

**Closed by stuartmorgan** 2019-07-08 12:37 UTC
