### ISSUE TITLE
[macos] Failed run Flutter desktop embedding

### ISSUE THREAD

**Issue by git-maspaad** [google/flutter-desktop-embedding#501] opened 2019-08-24 09:46 UTC
This happen, after I try to add package **cached_network_image** into pubspec.yaml

** BUILD FAILED **
The following build commands failed: PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks

/Users/macosx/flutterdesktop/example/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Script-DEC06400FA92971C0712BDA9.sh
(1 failure)
Building macOS application...
Build process failed

**Comment by stuartmorgan** [comment] 2019-08-24 12:46
`cached_network_image` has a transitive dependency on `sqflite`, which is a plugin. See https://flutter.dev/desktop#plugins

**Comment by stuartmorgan** [comment] 2019-08-24 14:26
Re-opening for investigation; while the plugin won't work, that should be a runtime exception, not a build error. Pod install should just be skipping unsupported plugins, so something is definitely wrong here.

**Comment by stuartmorgan** [comment] 2019-08-24 14:29
I'm not able to reproduce this by adding `cached_network_image` to the example project's pubspec.yaml. I'm seeing pod install run and just not install anything, as expected. Could you provide the full `flutter run -v` output?

**Comment by lucacasonato** [comment] 2019-08-24 19:03
I had the same issue a few days ago but managed to find out what the actual issue is by running `flutter build bundle` which displayed the actual error. Maybe the `Script-xxx.sh` should actually print the error that occurred.

**Comment by stuartmorgan** [comment] 2019-08-24 20:01
> Maybe the Script-xxx.sh should actually print the error that occurred.

The Xcode script phases don't do any output redirection. The problem is not the script phase, it's that `flutter run` without verbose mode doesn't surface enough information from that output stream on macOS (https://github.com/flutter/flutter/issues/33582).

**Comment by git-maspaad** [comment] 2019-08-25 16:46
Hi @stuartmorgan thanks for help and suggestions.
This is my current success of desktop app with flutter.

![Screen Shot 2019-08-24 at 22 38 34](https://user-images.githubusercontent.com/33727072/63653085-63800e00-c792-11e9-8707-6e340b1556c4.png)
Picture - 1

![Screen Shot 2019-08-24 at 22 40 34](https://user-images.githubusercontent.com/33727072/63653089-772b7480-c792-11e9-89b0-5672dc60547e.png)
Picture - 2

**Comment by stuartmorgan** [comment] 2019-08-25 20:44
If it's building now, closing; if you're not able to reproduce the error to get the full log, there's no way to investigate further.

**Closed by stuartmorgan** 2019-08-25 20:44 UTC
