### ISSUE TITLE
choosefile error on windows

### ISSUE THREAD

**Issue by Slihao** [google/flutter-desktop-embedding#717] opened 2020-04-17 01:21 UTC
路径：C:\Users\Administrator\Documents
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\lib\ui\ui_dart_state.cc(157)] Unhandled Exception: PlatformException(System error, Could not create dialog, -2147221008)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:342:40)
#4      FileChooserChannelController.show (package:file_chooser/src/channel_controller.dart:149:34)
#5      showOpenPanel (package:file_chooser/src/utilities.dart:42:8)
#6      _CommonChatPageState.fileChoose (package:duchat/home/message/CommonChatPage.dart:212:26)

**Comment by stuartmorgan** [comment] 2020-04-17 02:19
Duplicate of https://github.com/google/flutter-desktop-embedding/issues/716

**Closed by stuartmorgan** 2020-04-17 02:19 UTC
