### ISSUE TITLE
Unhandled text input method 'TextInput.setEditableSizeAndTransform'

### ISSUE THREAD

**Issue by mtcliatt** [google/flutter-desktop-embedding#618] opened 2019-12-03 21:16 UTC
This exception is thrown in our application for every scroll event that happens while a text field is focused. When running the testbed application, the exception seems to only be thrown when the text fields are initially focused.

```
[ +429 ms] 2019-12-03 13:13:22.243 Testbed[12070:65139] Unhandled text input method 'TextInput.setEditableSizeAndTransform'
[        ] 2019-12-03 13:13:22.243 Testbed[12070:65139] Unhandled text input method 'TextInput.setStyle'
```

**Comment by stuartmorgan** [comment] 2019-12-04 02:03
Duplicate of #40427. Any change would be in either the engine or the framework, so nothing is necessary at the level of this repository.

**Closed by stuartmorgan** 2019-12-04 02:03 UTC

**Comment by krisgiesing** [comment] 2019-12-04 02:04
https://github.com/flutter/flutter/issues/40427 since auto-linking doesn't work between github repositories.
