### ISSUE TITLE
[linux] Rendering issues after switching desktops

### ISSUE THREAD

**Issue by handicraftsman** [google/flutter-desktop-embedding#111] opened 2018-07-19 13:25 UTC
`flutter_embedder_example` application manages to fully load one of my CPU cores.
Also after switching desktops it usually looks like this until i resize it or press any button in the gui:
![_2018-07-19_16-24-02](https://user-images.githubusercontent.com/6382804/42945135-37aecca8-8b70-11e8-87af-d2c38310f2f4.png)

**Comment by stuartmorgan** [comment] 2018-07-21 19:40
CPU is a duplicate of issue #58; retitling for the rendering issue.

> Also... any plans on packaging (.deb/.rmp/.tar.gz) script support?

Please file a separate report for each bug or feature request.

**Comment by handicraftsman** [comment] 2018-07-22 08:04
Regarding rendering issue: it works almost as intended if focus is within a text field.

**Comment by stuartmorgan** [comment] 2018-12-28 16:33
I haven't experimented with this, but it's likely that we need use `glfwSetWindowRefreshCallback` to set something that triggers a Flutter redraw.

@chinmaygarde is there any way to request a redraw via the embedding API, other than setting the window size again?

**Comment by GeertJohan** [comment] 2018-12-28 17:20
@stuartmorgan I think perhaps sending `AppLifecycleState.resumed` message on the `flutter/lifecycle` channel would trigger re-render. See https://github.com/flutter/engine/blob/master/shell/common/engine.cc#L291

**Comment by dballesteros7** [comment] 2019-03-04 10:58
I am seeing this issue as well and adding a glfwSetWindowRefreshCallback fixes it. I hacked the callback to send a FlutterWindowMetricsEvent with the same size as current and that triggers a re-render.

But I'd be great to have that as part of the embedder API.

**Comment by stuartmorgan** [comment] 2019-03-04 15:34
If you'd like to send that as a PR I'm fine with that as a workaround until there's something more specific in the engine API.

**Comment by stuartmorgan** [comment] 2019-04-08 20:30
Moved to https://github.com/flutter/flutter/issues/30731

**Closed by stuartmorgan** 2019-04-08 20:30 UTC
Labels: bug
