### ISSUE TITLE
German 'umlaut's in the built filepath crashes the application. 

### ISSUE THREAD

**Issue by jkoenig134** [google/flutter-desktop-embedding#652] opened 2020-01-26 17:51 UTC
I know, umlaut's shouldn't be used in development.
But if i put the built binaries in a folder containing ü or ö the application window pops up and crashes.
I think there is a problem in finding the binaries and assets.

**Comment by stuartmorgan** [comment] 2020-01-27 00:21
Possibly a duplicate of https://github.com/flutter/flutter/issues/49372, but if it's actually crashing there may be more bugs at higher levels. Leaving open until we can verify whether the runners are okay. If nothing else, I should take this opportunity to change the `codecvt` code in `GetExecutableDirectory()` since based on more recent research I don't think that conversion is quite right.

**Comment by stuartmorgan** [comment] 2020-01-27 00:22
> and also flutter for desktop (windows) shouldn't be used

I'm not sure what this means; this project has a runner for Windows, and instructions for using that Runner, for a reason...

**Comment by jkoenig134** [comment] 2020-01-27 04:45
I meant because it's in an early state.

**Comment by stuartmorgan** [comment] 2020-01-27 19:28
Tested locally, and it's not crashing, it's logging and exiting out [here](https://github.com/google/flutter-desktop-embedding/blob/6db1b577157d32f8847d8497fdf2eecc1b849dcf/example/windows/main.cpp#L81), so this is just flutter/flutter#49372. (In the future, it would be helpful if you could include console output when reporting issues.)

Posted https://github.com/google/flutter-desktop-embedding/pull/653 for the `codecvt` issue mentioned above, but that wasn't coming into play here.

**Closed by stuartmorgan** 2020-01-27 19:28 UTC
Labels: os-windows
