### ISSUE TITLE
Add build documentation

### ISSUE THREAD

**Issue by JakeSays** [google/flutter-desktop-embedding#520] opened 2019-08-29 20:18 UTC
I cannot find any build instructions. Specifically I would like to know what needs to be passed to the makefiles to allow a custom flutter engine build.

**Comment by stuartmorgan** [comment] 2019-08-29 21:19
I'm not sure what you're asking for exactly. [These](https://github.com/google/flutter-desktop-embedding#running-a-project) are the build instructions.

> to allow a custom flutter engine build

Do you mean running one of the FDE examples with a locally built embedding library? It's [the same as for any other platform](https://github.com/flutter/flutter/wiki/Compiling-the-engine#running-a-flutter-app-with-a-local-engine).

**Comment by JakeSays** [comment] 2019-08-29 22:00
@stuartmorgan `flutter run` is all I see. Nothing on how to build the embedders/runners themselves. And you say as far as any other platform - so how to I reference my engine headers and .so's? Is `flutter run` supposed to do all of this for me? If so, that's not what I need. I need to build the c++ components outside of the flutter tool.

**Comment by stuartmorgan** [comment] 2019-08-29 22:16
> `flutter run` is all I see. Nothing on how to build the embedders/runners themselves.

`flutter run` builds the runner.

> how to I reference my engine headers and .so's?

I'm still not understanding what you are asking. What do you mean "my engine headers and .so's"? If you have made local modifications to the desktop embedding in a local engine build, using `--local-engine` will refer to the built copy, per the instructions I linked to above (just as with iOS or Android).

> I need to build the c++ components outside of the flutter tool.

I'm not sure what this is referring to. What C++ components? Are you talking about adding code to the engine, or to the runner? Or are you trying to do add-to-app?

> However the desktop examples do not follow the traditional pattern of building embedders.

I think you may be conflating [custom engine embedders](https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders) with the Flutter platform embeddings. This project uses the latter.


It would be helpful if you could provide context on what it is you are trying to accomplish, because I'm still not clear on what it is that you want to do and what instructions you think are missing.

**Comment by JakeSays** [comment] 2019-08-29 22:19
Ok yes I am confusing embedders with platforms. What I am trying to do is create my own runner, without using flutter run to build it. I have my own toolset, compilers, etc. and a workflow I would prefer not to change. Basically I want to treat building the runner as I would any other c++ project.

**Comment by stuartmorgan** [comment] 2019-08-29 22:24
That sounds like you want add-to-app, but then I'm confused by your initial comment about "allow a custom flutter engine build". Are you trying to use the prebuilt Linux desktop embedding (which would *not* be a custom engine build), just with your own runner, or are you trying to use both your own runner and a custom build of the embeddings?

**Comment by JakeSays** [comment] 2019-08-29 22:26
Custom build of libflutter_linux_glfw.so and my own runner.

I am not at this moment trying to add to an app.

**Comment by stuartmorgan** [comment] 2019-08-29 22:59
If you want a supported/streamlined way of using the `flutter` tool to create a Flutter "module" (for lack of a better term) that you can consume in a well-defined way from an arbitrary native application that's not created by `flutter create` or built/managed via `flutter build` and `flutter run`, that is exactly add-to-app. Even if the app you're "adding" to is currently empty, it's still the add-to-app flow. If that's what you want, this is a duplicate of #414 (although as noted there, I don't have any plan to try to support that for GLFW).

However, at this point all the Flutter tooling on Linux is really doing is:
- Getting the right engine artifacts
  - Since you are doing a custom build of the library, this is irrelevant to you.
- Building the example Runner code
  - You explicitly don't want this part
- [Running `flutter build bundle`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/tool_backend.dart#L67)
  - That's just a `flutter` tool command, and not part of this project, so not something I would document here.

I'm still confused by exactly what you're expecting this project to provide that's relevant to your use case. You said:
> I have my own toolset, compilers, etc. and a workflow I would prefer not to change. Basically I want to treat building the runner as I would any other c++ project.

but then:
> how to I reference my engine headers and .so's?

If you want to use entirely your own workflow and toolset, to link a library that you are building locally already, the the answer to that question is: however you would link to any other C library in the toolchain you are using.

**Comment by JakeSays** [comment] 2019-08-29 23:11
I don't need supported/streamlined `flutter` workflow, etc. It won't work for my use-case (which is using flutter on small embedded devices). I am creating a "device emulator" kind of tool that has special functionality specific to my needs. `flutter create` and `flutter build` - those work fine as is. It's as simple as this: what do I need to pass to this makefile (https://github.com/google/flutter-desktop-embedding/blob/master/example/linux/Makefile) to get it to build the runner against my `libflutter_linux_glfw.so` build. There's a lot in that makefile - I'm sure more than I need, but for now I just need to build the dang thing using make (I want to use gn, but I can handle that later).

**Comment by stuartmorgan** [comment] 2019-08-29 23:18
That makefile is specifically for building the stock runner, which you said you don't want, with `flutter build` or `flutter run` which you said you don't want. I don't understand why you are trying to use it at all.

**Comment by JakeSays** [comment] 2019-08-29 23:26
I want to use it because it's in the source tree. 99.9% of the time when a c/c++ dev sees a makefile they figure that's what should be used. However this one isn't complete - it references some mystery generated config file.

The bottom line is flutter run is a black mystery box. It would be really nice if we could understand what it does.

If the makefile is specific to flutter run/build then document it or call it something else. I don't know. I was under the (apparently incorrect) assumption that the desktop stuff was just another c++ project that we could do with what we wanted - perhaps from it starting as a separate project from flutter.

**Closed** 2019-08-29 23:27 UTC

**Comment by stuartmorgan** [comment] 2019-08-29 23:48
If you want to hack something together to use the Makefile without using `flutter build`, https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/linux/build_linux.dart#L22 is what that config would be populated by. You could make it manually. (You could also have just followed the instructions once, and then looked at what was in the file.)

> I want to use it because it's in the source tree.

It's in the source tree because: "The linux, macos, and windows directories serve as early prototypes of what will eventually become the flutter create templates for desktop" (From the very start of the `example` README.)

> 99.9% of the time when a c/c++ dev sees a makefile they figure that's what should be used.

The READMEs for this project have explicit build instructions. I do not believe that it's the case that 99.9% of developers expect that they can take arbitrary parts of a project's build system and run it without following the project's instructions.

> However this one isn't complete - it references some mystery generated config file.

Which is consistent with how the projects created by the `flutter create` templates for iOS and Android work as well.

> The bottom line is flutter run is a black mystery box. It would be really nice if we could understand what it does.

I still believe that add-to-app, if it existing for desktop at this point, would address most of your issues.

> I was under the (apparently incorrect) assumption that the desktop stuff was just another c++ project that we could do with what we wanted

You are referring to two disjoint things as "the desktop stuff".
- The Linux embedding is, in fact, just a C++ project. You can check it out, it has a build system, it produces a .so and some headers, and you can build it and then do whatever you want with it.
- This project is not. Its README specifically says that it's just an example/testbed, and also that it's a proto-template for `flutter create`. https://github.com/flutter/flutter/wiki/Desktop-shells#using-the-shells, which this project links to, explains that as well.

**Comment by JakeSays** [comment] 2019-08-30 03:16
Ok. Nowhere in these readme's you speak of does it mention how to build the runner. `flutter run` *runs* the example, not *builds* it. I just wanted to know how the runner was built. That's it. Your documentation is extremely vague on how to do that. Forgive me for expecting more than I should have - I am used to the documentation of the other c++ components of flutter (the engine and embedders) being quite good in regard to how the native pieces are built. `flutter run` explains nothing.

Anyway, sorry for wasting your time. I won't make that mistake again.

**Comment by stuartmorgan** [comment] 2019-08-30 03:37
> Nowhere in these readme's you speak of does it mention how to build the runner. flutter run runs the example, not builds it.

True, thanks for flagging that. I've updated the `example` README to mention it. Since the project now uses normal Flutter tooling, and I assume people interested in the project are familiar with Flutter, I hadn't documented operations other than the simplest getting-started flow.

> I just wanted to know how the runner was built. That's it.

One of the very first things you said was "I need to build the c++ components outside of the flutter tool", which is why I didn't mention `flutter build`. If you had said that you wanted to know how to build without running, rather than specifically saying that you didn't want to use the `flutter` tool to build, this would have been a much shorter discussion.

> All the flutter example readme says is that it's a template for a desktop application. 

That's not what it says though. What it actually says is that it they are "early prototypes of what will eventually become the `flutter create` templates". And the `flutter create` templates make projects that behave exactly like this.

> Coming from a c++ background

It is certainly the case that the documentation here assumes a Flutter background, not a generic C++ development background. That's because the original version of this project was much more like what you seem to be expecting, and *overwhelmingly* the feedback was that people coming to the project were people with Flutter backgrounds, not C++ development backgrounds. They found the instructions confusing and unhelpful, and consistently asked for `flutter run` support instead of requiring direct interaction with native build systems. The project's focus, and documentation, changed accordingly.

I'm happy to help people interested in using Flutter on desktop in other ways, but being upset that the focus is on the 99% use case that people were coming to the project wanting is not a constructive way to engage to get help with the 1%.
