### ISSUE TITLE
[DOUBT] How do I create shortcut keys in my Flutter Desktop application?

### ISSUE THREAD

**Issue by Lucasoliviersystem** [google/flutter-desktop-embedding#570] opened 2019-09-20 17:14 UTC
Hi !

How do I create shortcut keys in my Flutter Desktop application? its possible?

e.g. Ctrl + F10 , or just F10. 

thks []

**Comment by stuartmorgan** [comment] 2019-09-20 20:50
Duplicate of https://github.com/flutter/flutter/issues/31946

**Closed by stuartmorgan** 2019-09-20 20:50 UTC
