### ISSUE TITLE
Auto-Update flutter desktop app like Discord and Telegram desktop apps

### ISSUE THREAD

**Issue by Lazizbek97** [google/flutter-desktop-embedding#909] opened 2022-10-01 07:35 UTC
### Is this request within the scope of this project?

- [X] I have read [the README section about feedback](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback).
- [X] My request is specifically related to this repository, not Flutter's desktop support.

### Which plugin is this request about?

A proposal for a new experimental plugin

## A clear and concise description of what the problem is:
After I distribute the app to clients, of course, I would want to add some new features or fix some bugs. At that time, I have to send newly released versions of the app to clients in dmg or in exe file types. But it's really frustrating for me and my clients.

## Describe the feature you'd like:
So I want to add auto-updating whenever the app starts like discord or telegram desktop apps.
How can I implement it? Does your app support such a feature? if not, could you please implement it? so that i can learn it and copy it to my own desktop apps ).
I have been searching for a solution to this problem for months... That would be great if you can help me and people who are facing the same problems.

By the way: msix package would be somehow a solution BUT to install msix packages user should have pfx certificate. As you know first users don't have that package and even if they have, to make the certificate trusted is so complex for users.
Thanks.

**Comment by cbenhagen** [comment] 2022-10-01 16:05
Hi

Please only file issues related to the plugins in this repository.

You might be interested in https://pub.dev/packages/auto_updater and https://pub.dev/packages/flutter_distributor

**Comment by stuartmorgan** [comment] 2022-10-03 13:45
Duplicate of https://github.com/google/flutter-desktop-embedding/issues/469.

> Does your app support such a feature?

This repository doesn't contain any production applications.

**Closed by stuartmorgan** 2022-10-03 13:45 UTC
