### ISSUE TITLE
[windows] Example crashes on launch

### ISSUE THREAD

**Issue by n8crwlr** [google/flutter-desktop-embedding#525] opened 2019-09-02 20:39 UTC
I have no idea.

Thats Windows 10, Visual Studio Community 2019. All is newest available.

The App is only starting and closing. I have tried on an older Windows installation and a completely new - everything installed from ground up.

![flutter-win](https://user-images.githubusercontent.com/54250425/64132611-40c4a980-cdd1-11e9-9dcf-a133fbf7a45f.gif)

`Building Windows application...`
`Syncing files to device windows`
`This is taking an unexpectedly long time`

**Comment by stuartmorgan** [comment] 2019-09-02 21:01
Please run the application from within Visual Studio, and provide the stack trace from the crash.

(In the future, please post logs, not animated GIFs of screencasts of the entire setup process; it's much harder to investigate when I have to watch the entire setup in realtime before getting to the relevant section.)

**Comment by n8crwlr** [comment] 2019-09-03 18:00
```bash
Unhandled exception at 0x00007FFEB91E24D8 (flutter_windows_glfw.dll)
in Flutter Desktop Example.exe: 0xC0000005: Access violation
writing location 0x0000000090DC6000. occurred
```

**Comment by stuartmorgan** [comment] 2019-09-03 18:10
This may be #457. Could you follow the instructions [here](https://github.com/google/flutter-desktop-embedding/issues/457#issuecomment-512360416) to get symbols (updating the destination path for your project, of course), and provide the full symbolicated stack?

**Comment by n8crwlr** [comment] 2019-09-03 20:41
Hmm, ok, i got something comparable 👍 

```bash
flutter_windows_glfw.dll!GrResourceProvider::createPatternedIndexBuffer(const unsigned short * pattern=0x00007ffea65e2580, int patternSize, int reps=4096, int vertCount=4, const GrUniqueKey * key=0x0000000000000000) Line 478	C++
flutter_windows_glfw.dll!GrResourceProvider::createQuadIndexBuffer() Line 500	C++
flutter_windows_glfw.dll!GrResourceProvider::refQuadIndexBuffer() Line 213	C++
flutter_windows_glfw.dll!GrSmallPathRenderer::SmallPathOp::onPrepareDraws(GrMeshDrawOp::Target * target=0x0000007daf0fda78) Line 382	C++
[Inline Frame] flutter_windows_glfw.dll!GrOp::prepare(GrOpFlushState *) Line 160	C++
flutter_windows_glfw.dll!GrOpsTask::onPrepare(GrOpFlushState * flushState=0x0000007daf0fda70) Line 413	C++
flutter_windows_glfw.dll!GrDrawingManager::executeRenderTasks(int startIndex, int stopIndex=1, GrOpFlushState * flushState=0x0000007daf0fda70, int * numRenderTasksExecuted=0x0000007daf0fda10) Line 429	C++
flutter_windows_glfw.dll!GrDrawingManager::flush(GrSurfaceProxy * * proxies=0x0000007daf0ff628, int numProxies=1, SkSurface::BackendSurfaceAccess access=kNoAccess, const GrFlushInfo & info={...}, const GrPrepareForExternalIORequests & externalRequests={...}) Line 362	C++
flutter_windows_glfw.dll!GrDrawingManager::flushSurfaces(GrSurfaceProxy * * proxies=0x0000007daf0ff628, int numProxies, SkSurface::BackendSurfaceAccess access=kNoAccess, const GrFlushInfo & info={...}) Line 520	C++
[Inline Frame] flutter_windows_glfw.dll!GrDrawingManager::flushSurface(GrSurfaceProxy * proxy=0x00000201cb6a1ec8, SkSurface::BackendSurfaceAccess) Line 103	C++
flutter_windows_glfw.dll!GrRenderTargetContext::flush(SkSurface::BackendSurfaceAccess access=kNoAccess, const GrFlushInfo & info={...}) Line 1982	C++
[Inline Frame] flutter_windows_glfw.dll!SkGpuDevice::flush(SkSurface::BackendSurfaceAccess) Line 1597	C++
flutter_windows_glfw.dll!SkGpuDevice::flush() Line 1591	C++
flutter_windows_glfw.dll!SkCanvas::onFlush() Line 617	C++
[Inline Frame] flutter_windows_glfw.dll!flutter::?A0x85672993::MakeRasterSnapshot(sk_sp<SkPicture>) Line 54	C++
flutter_windows_glfw.dll!flutter::Picture::RasterizeToImage::__l2::<lambda>() Line 179	C++
[Inline Frame] flutter_windows_glfw.dll!std::_Func_class<void>::operator()() Line 121	C++
flutter_windows_glfw.dll!fml::MessageLoopImpl::FlushTasks(fml::FlushType type=kAll) Line 123	C++
flutter_windows_glfw.dll!fml::MessageLoopWin::Run() Line 23	C++
flutter_windows_glfw.dll!fml::MessageLoopImpl::DoRun() Line 95	C++
flutter_windows_glfw.dll!fml::MessageLoop::Run() Line 50	C++
[External Code]	
flutter_windows_glfw.dll!thread_start<unsigned int (__cdecl*)(void *),1>(void * const parameter=0x00000201ca20b910) Line 97	C++
[External Code]	
```

It asks also for the same file:

![image](https://user-images.githubusercontent.com/54250425/64206653-3969d280-ce9b-11e9-8622-1b01d0897f04.png)

Which is, too, HD3000:

![image](https://user-images.githubusercontent.com/54250425/64206698-56060a80-ce9b-11e9-845b-4dc3c1088e78.png)

There is an nvidia gpu, too, which is disabled via BIOS.

Intel HD 3000 Grafik
Nvidia NVS 4200M, 1GB VRAM, Optimus

**Comment by stuartmorgan** [comment] 2019-09-03 20:49
Yes, that's the same issue (and at this point we do believe that it's specific to that GPU). Closing as a duplicate of flutter/flutter#34556. You can follow there (and in the Skia bug linked from there) for updates.

**Closed by stuartmorgan** 2019-09-03 20:49 UTC

**Comment by n8crwlr** [comment] 2019-09-03 21:16
OK, thanks for the guidiance 👍
