### ISSUE TITLE
Flutter windows app for Surface pro not showing the keyboard.

### ISSUE THREAD

**Issue by shaikfareed46** [google/flutter-desktop-embedding#608] opened 2019-11-19 12:42 UTC
Hi,

I have been developing app for windows using flutter. Everything is working fine in windows laptop having keyboard attached. 

However, The same thing is **not working on a windows surface pro** where there will be **on screen keyboard**. 

The issue is related to TextFormField behavior for Surface pro. The cursor appears when i click on form field but there is no On Screen keyboard to enter the details.

**Expected Behavior:**
TextFormField is appearing
Able to see onscreen keyboard
Able to enter text using onscreen keyboard

**Actual Behavior:**
TextFormField is appearing
no onscreen keyboard
Manually if i enable onscreen keyboard it works

Kindly let me know if there is anything that i am missing. 

FYI, I have installed all the Visual Studio libraries required to run flutter app for windows.

Manually if I tap on enable onscreen keyboard, Onscreen keyboard appears and I am able to enter

Thank you

**Comment by stuartmorgan** [comment] 2019-11-19 14:27
Duplicate of https://github.com/flutter/flutter/issues/36057

**Closed by stuartmorgan** 2019-11-19 14:27 UTC
