### ISSUE TITLE
Can't make Mac build for my flutter app

### ISSUE THREAD

**Issue by zazu27** [google/flutter-desktop-embedding#312] opened 2019-03-25 08:29 UTC
I replace "lib" library in the example package, yaml and pod files. Can't find FlutterMacOS.h when run ExampleEmbedder. How can I find FlutterMacOS.framework? How can I make Mac build? 
Thanks!

**Comment by stuartmorgan** [comment] 2019-03-25 12:38
> Can't find FlutterMacOS.h when run ExampleEmbedder.

Please provide your build log; if this file is missing, there were almost certainly errors in an earlier step.

**Comment by iNoles** [comment] 2019-03-26 23:30
I had this problem when it was looking for specific flutter engines that is found on the master branch.

**Comment by stuartmorgan** [comment] 2019-03-27 00:47
> when it was looking for specific flutter engines that is found on the master branch.

Meaning that you had an error during the build telling you that your Flutter tree was too old? If so, that's behaving as expected.

**Comment by RazaGR** [comment] 2019-04-03 12:50
> > when it was looking for specific flutter engines that is found on the master branch.
> 
> Meaning that you had an error during the build telling you that your Flutter tree was too old? If so, that's behaving as expected.

I had the same issue `Can't find FlutterMacOS.h ` which was fixed by switching flutter channel by `flutter channel master`

@stuartmorgan  does this embedding use chromium behind the scene? if so any particular URL available? I need somehow to embed the output to my electron app

**Comment by stuartmorgan** [comment] 2019-04-03 13:19
Again, this should have also resulted in an earlier error explicitly saying that your Flutter tree is not new enough and to switch to master. Assuming it did, this is expected behavior, because that error indicates that it could not download the framework that contains the header. Since that seems to be what happened to others seeing this, closing absent a response indicating otherwise.

> @stuartmorgan does this embedding use chromium behind the scene?

This is unrelated to the topic of this bug, and would be better suited to the mailing list, but the answer is no.

**Closed by stuartmorgan** 2019-04-03 13:19 UTC
