### ISSUE TITLE
Latest code of flutter and flutter-desktop-embedding with master branch, flutter run error

### ISSUE THREAD

**Issue by GanZhiXiong** [google/flutter-desktop-embedding#494] opened 2019-08-21 07:06 UTC
![image](https://user-images.githubusercontent.com/27394631/63409911-a786b200-c424-11e9-833a-67f5315aad5f.png)

![image](https://user-images.githubusercontent.com/27394631/63410115-24b22700-c425-11e9-95e3-2c6bbf0ff44c.png)

**Comment by jonahwilliams** [comment] 2019-08-21 07:11
See the error message: "Exception: Failed to create symlinks for framework. try removing ../macos/Flutter/ephemeral and rerunning"

**Comment by GanZhiXiong** [comment] 2019-08-21 07:39
@jonahwilliams  I tried as you said, but I still reported the following error

![image](https://user-images.githubusercontent.com/27394631/63412177-c0de2d00-c429-11e9-817e-d0e6f51e7b38.png)

**Comment by jonahwilliams** [comment] 2019-08-21 07:41
That is a different error, and a duplicate of https://github.com/google/flutter-desktop-embedding/issues/487

**Closed by jonahwilliams** 2019-08-21 07:41 UTC

**Comment by GanZhiXiong** [comment] 2019-08-21 07:49
Is this problem easy to solve? When can it be resolved?
