### ISSUE TITLE
Unable to find a plugin.vcxproj for plugin "window_size"

### ISSUE THREAD

**Issue by brilliapps** [google/flutter-desktop-embedding#772] opened 2020-07-08 14:31 UTC
**Describe the bug**
Not very experienced github and flutter user but on windows 10 i have this
flutter run -d windows
Unable to find a **plugin.vcxproj** for plugin "window_size". Google doesn't help much about this **plugin.vcxproj**
I see in the issues section there are people having this working, not like me.
My pubspec.yaml i have this:
dependencies:
  flutter:
    sdk: flutter
  process_run: ^0.10.10+2
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: #770
  cupertino_icons: ^0.1.3

**Doctor Output**
Please provide the output of `flutter doctor -v`:
```
```

**Comment by stuartmorgan** [comment] 2020-07-08 14:47
Duplicate of #769

**Closed by stuartmorgan** 2020-07-08 14:47 UTC
