### ISSUE TITLE
[GLFW] Repeating Key Event is Input Blocking

### ISSUE THREAD

**Issue by CallumIddon** [google/flutter-desktop-embedding#294] opened 2019-02-26 02:09 UTC
When you hold down a key all other input (such as mouse events) isn't sent to the app. I am currently unsure if this applies to all unknown input types or just the repeating key event.

```dart
Center(
    child: GestureDetector(
        onTapDown: (TapDownDetails details) => print('Tapped!'),
        child: Container(color: Colors.blue, height: 50, width: 50)
    )
)
```

Take the above code snippet. If you click on the blue square it will print "Tapped!", but if you hold down a key and click on it that doesn't happen. I have tried disabling the "Unknown key event action: 2" message and sending a blank key event to Flutter when a `GLFW_REPEAT` event occurs but it still persists.

I believe that this action does work on mac as the [flutter/slideplayer](https://github.com/flutter/slideplayer) app allows you to change slides by holding the "z" key and clicking on the slide you want to change to.

**Comment by stuartmorgan** [comment] 2019-02-26 06:16
Is `GLFWMouseButtonCallback` called in that scenario? It may be a GLFW input handling limitation; I'm not familiar enough with GLFW to know offhand.

Given that the current implementation doesn't send anything to the engine for repeat (given that message), I'd be very surprised if this is on the Flutter side.

> I believe that this action does work on mac

Since we're using the platform event processing directly, which definitely support this, I'd be surprised if it didn't.

**Comment by CallumIddon** [comment] 2019-02-27 20:53
Looks to be an OS issue as this happens in other applications as well. My current OS install won't let me enable the touchpad while typing on my computer with other applications so I cannot be sure if this is actually an issue or not.

**Comment by stuartmorgan** [comment] 2019-04-08 16:43
> Looks to be an OS issue as this happens in other applications as well.

That seems to be the case, because I can successfully click in the Linux example while holding down a key. Given that the issue is specific to your OS, not the shell, closing.

**Closed by stuartmorgan** 2019-04-08 16:43 UTC
Labels: bug
