### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by thesmartrenovation** [google/flutter-desktop-embedding#673] opened 2020-02-14 13:51 UTC
Hi,

I can't to run teh example in windows. look:

`[  +32 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +78 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 85ab331c8226dc154c8f1f038be707d917dfbeee
[        ] executing: [C:\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +75 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.15.3-68-g85ab331c8
[   +9 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +48 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +93 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +47 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] executing: C:\Users\Fabian\Android\sdk\platform-tools\adb.exe devices -l
[  +33 ms] Exit code 0 from: C:\Users\Fabian\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +15 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +314 ms] Launching lib\main.dart on Windows in debug mode...
[  +30 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -version 16 -requires Microsoft.Component.MSBuild
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[ +138 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -version 16 -requires Microsoft.Component.MSBuild
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[   +3 ms] [
             {
               "instanceId": "f3a57ce5",
               "installDate": "2019-12-04T23:44:06Z",
               "installationName": "VisualStudio/16.4.0+29519.181",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.4.29519.181",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.4.0",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2019-12-04T23:44:06.2777888Z",
               "catalog": {
                 "buildBranch": "d16.4",
                 "buildVersion": "16.4.29519.181",
                 "id": "VisualStudio/16.4.0+29519.181",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.4.0",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "0",
                 "productPreReleaseMilestoneSuffix": "7.0",
                 "productSemanticVersion": "16.4.0+29519.181",
                 "requiredEngineVersion": "2.4.1111.43337"
               },
               "properties": {
                 "campaignId": "1718383653.1570478860",
                 "canceled": "0",
                 "channelManifestId": "VisualStudio.16.Release/16.4.0+29519.181",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[  +37 ms] Building Windows application...
[   +6 ms] executing: [C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows/] C:\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
[ +354 ms] **********************************************************************
[   +1 ms] ** Visual Studio 2019 Developer Command Prompt v16.4.0
[        ] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[+1038 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +110 ms] Microsoft (R) Build Engine versión 16.4.0+e901037fe para .NET Framework
[        ] Copyright (C) Microsoft Corporation. Todos los derechos reservados.
[  +17 ms] Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "-m".
[ +261 ms] Compilación iniciada a las 14/02/2020 8:50:42 a. m..
[ +704 ms] Proyecto "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.sln" en nodo 1 (destinos predeterminados).
[   +6 ms] ValidateSolutionConfiguration:
[        ]   Compilando la configuración de soluciones "Debug|x64".
[ +370 ms] El proyecto "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.sln" (1) está compilando
"C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.vcxproj.metaproj" (2) en el nodo 1 (destinos predeterminados).
[   +1 ms] El proyecto "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.vcxproj.metaproj" (2) está compilando
"C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\FlutterBuild.vcxproj" (3) en el nodo 1 (destinos predeterminados).
[  +11 ms] InitializeBuildStatus:
[        ]   Se creará "x64\Debug\Flutter Build.tlog\unsuccessfulbuild" porque se especificó "AlwaysCreate".
[  +26 ms] CustomBuildStep:
[   +4 ms]   Running Flutter backend build
[  +14 ms]   "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\scripts\prepare_dependencies" Debug
[   +2 ms]   :VCEnd
[+7088 ms] FinalizeBuildStatus:
[   +2 ms]   Se eliminará el archivo "x64\Debug\Flutter Build.tlog\unsuccessfulbuild".
[   +1 ms]   Aplicando tarea Touch a "x64\Debug\Flutter Build.tlog\Flutter Build.lastbuildstate".
[   +2 ms] Compilación del proyecto terminada "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\FlutterBuild.vcxproj" (destinos predeterminados).
[  +68 ms] El proyecto "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.vcxproj.metaproj" (2) está compilando
"C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.vcxproj" (4) en el nodo 1 (destinos predeterminados).
[   +1 ms] InitializeBuildStatus:
[        ]   Aplicando tarea Touch a "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild".
[ +110 ms] ClCompile:
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\CL.exe /c /ZI /JMC /nologo /W4 /WX /diagnostics:column /sdl /Od /D _MBCS /D
_HAS_EXCEPTIONS=0 /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline
/Fo"C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\..\build\windows\intermediates\x64\Debug\Runner\\"
/Fd"C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\..\build\windows\intermediates\x64\Debug\Runner\vc142.pdb" /Gd /TP /wd4100 /FC /errorReport:queue main.cpp
flutter\generated_plugin_registrant.cc win32_window.cc "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\flutter\ephemeral\cpp_client_wrapper\engine_method_result.cc"
"C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\flutter\ephemeral\cpp_client_wrapper\plugin_registrar.cc"
[  +91 ms]   main.cpp
[+1139 ms]   generated_plugin_registrant.cc
[ +257 ms]   win32_window.cc
[ +620 ms] C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\win32_window.cc(57,14): error C3861: 'FlutterDesktopGetDpiForMonitor': no se encontró el identificador
[C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.vcxproj]
[   +1 ms]   engine_method_result.cc
[ +511 ms]   plugin_registrar.cc
[ +665 ms]   Generando código...
[ +229 ms] Compilación del proyecto terminada "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.vcxproj" (destinos predeterminados) -- ERROR.
[        ] Compilación del proyecto terminada "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.vcxproj.metaproj" (destinos predeterminados) -- ERROR.
[        ] Compilación del proyecto terminada "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.sln" (destinos predeterminados) -- ERROR.
[  +16 ms] ERROR al compilar.
[   +3 ms] "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.sln" (destino predeterminado) (1) ->
[        ] "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.vcxproj.metaproj" (destino predeterminado) (2) ->
[        ] "C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.vcxproj" (destino predeterminado) (4) ->
[        ] (ClCompile destino) -> 
[        ]   C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\win32_window.cc(57,14): error C3861: 'FlutterDesktopGetDpiForMonitor': no se encontró el identificador
[C:\Users\Fabian\Desktop\flutter-desktop-embedding-master\example\windows\Runner.vcxproj]
[   +1 ms]     0 Advertencia(s)
[        ]     1 Errores
[        ] Tiempo transcurrido 00:00:11.96
[  +32 ms] Building Windows application... (completed in 13,8s)
[   +2 ms] "flutter run" took 14.546ms.
Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:77:5)
<asynchronous suspension>
#2      WindowsDevice.buildForDevice (package:flutter_tools/src/windows/windows_device.dart:46:11)
#3      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:85:13)
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:434:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:333:39)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:681:18)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _rootRunUnary (dart:async/zone.dart:1134:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)`

Flutter Doctor:

`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.15.4-pre.68, on Microsoft Windows [VersiÃ³n 10.0.18362.657], locale es-CO)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[√] Connected device (3 available)

• No issues found!`

**Comment by stuartmorgan** [comment] 2020-02-14 14:34
Duplicate of #672

**Closed by stuartmorgan** 2020-02-14 14:34 UTC
