### ISSUE TITLE
Flutter SharedPreference plugin does not work in windows desktop app.

### ISSUE THREAD

**Issue by lodestar-sr** [google/flutter-desktop-embedding#692] opened 2020-03-04 09:54 UTC
@stuartmorgan Hello, 
In testbed project, you used shared_preference plugin, but I don't think this plugin works on window desktop app.
While I am running windows flutter app, I got this message in the console.

>Syncing files to device Windows...
Restarted application in 1,461ms.
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\lib\ui\ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
#0      Setting.getInstance (package:tiledmedia/data/models/setting.model.dart:21:43)
<asynchronous suspension>#1      _ProfilesState.initializeApp (package:tiledmedia/screens/profiles/profiles.dart:37:36)
#2      _ProfilesState.initState (package:tiledmedia/screens/profiles/profiles.dart:26:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5804:14)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5804:14)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5804:14)
...

How can I use shared_preference plugin in windows? 
Or what should I use to store data in windows flutter app?

**Comment by stuartmorgan** [comment] 2020-03-04 12:29
> In testbed project, you used shared_preference plugin

[Only on macOS](https://github.com/google/flutter-desktop-embedding/blob/94a9f2a43dc29989478c36755a88c604cb0265b1/testbed/lib/main.dart#L74)

Duplicate of #434

**Closed by stuartmorgan** 2020-03-04 12:29 UTC
