### ISSUE TITLE
fatal error: 'url_launcher_plugin.h' file not found #include <url_launcher_plugin.h>

### ISSUE THREAD

**Issue by hariom-dev** [google/flutter-desktop-embedding#668] opened 2020-02-12 04:57 UTC
I'm want implement url_launcher_fde on my windows and Linux desktop
my code is : 
url_launcher_fde:
  path: ./plugins/flutter_plugins/url_launcher_fde

when I run command flutter run -d linux it will return this error
Launching lib/main.dart on Linux in debug mode...
flutter/generated_plugin_registrant.cc:7:10: fatal error: 'url_launcher_plugin.h' file not found
#include <url_launcher_plugin.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [/home/ge-25/Projects/Flutter/Geitpl/flickERP/linux/../build/linux/obj/debug/flutter/generated_plugin_registrant.o] Error 1
Build process failed

**Comment by stuartmorgan** [comment] 2020-02-12 05:41
Please don't file a new bug for the same issue. Closing as a duplicate of #666.

**Closed by stuartmorgan** 2020-02-12 05:41 UTC
