### ISSUE TITLE
The flutter-desktop-embedding's programs can not run on windows7 64bit

### ISSUE THREAD

**Issue by biij5698** [google/flutter-desktop-embedding#568] opened 2019-09-19 14:43 UTC
flutter.bat run
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Then:
Nothing more.
But,when i click the program what is compiled by flutter-desktop-embedding,the error occured:
"无法启动此程序，因为计算机中丢失api-ms-win-shcore-scaling-l1-1-1.dll。尝试重新安装该程序以解决此问题。"

**Comment by stuartmorgan** [comment] 2019-09-19 15:29
This is a duplicate of https://github.com/flutter/flutter/issues/40855. Closing to track in one place (although if someone wants to enable support for Windows 7, I would expect patches would be needed in this repository as well).

**Closed by stuartmorgan** 2019-09-19 15:29 UTC
