### ISSUE TITLE
Adding a tray icon with hide and show functions

### ISSUE THREAD

**Issue by gdias1992** [google/flutter-desktop-embedding#804] opened 2020-10-11 04:53 UTC
Hello guys.

I know there are others discussion about this but i could not find any usefull information.

What i need is:

- Create a tray icon for my application.

- Be able to hide and show the application window through the tray icon right click menu.

- Add options to tray icon right click menu, like open screen X.

- Be able to start and stop my application, and change the tray icon on real time (see image below).

![github](https://user-images.githubusercontent.com/25283876/95670651-75726b00-0b64-11eb-9182-b2836ec9e5b8.PNG)

**P.S.: I don't know if Linux and MacOS supports tray icon, but i need at least the Windows implementation.**

Can someone guide me ? :D

Thanks all!

**Comment by stuartmorgan** [comment] 2020-10-11 06:34
To the extent that this is a feature request, this is a duplicate of #595.

> Can someone guide me ?

The issue tracker is not a help/discussion resource; it is for reporting bugs or filing feature requests related to the plugins in this repository.

**Closed by stuartmorgan** 2020-10-11 06:34 UTC
