### ISSUE TITLE
How do I "link the resulting framework into your application"?

### ISSUE THREAD

**Issue by TheOtherDave** [google/flutter-desktop-embedding#51] opened 2018-05-04 01:13 UTC
The directions at https://github.com/google/flutter-desktop-embedding/tree/master/macos don't make sense to me...

I've cloned 'flutter-desktop-embedding' next to 'flutter', and I've built "the Xcode project under library/". The part I'm stuck on is the "then link the resulting framework into your application" step... Not surprisingly, Dart's "import" command doesn't seem to work on frameworks. AFAIK, VS Code doesn't have anything analogous to .xcodeproj files, so there's no place to manually link it from the IDE and I can't find any settings in the dart files that look like they'd link anything.

Does anyone know what I'm doing wrong? When I open the Xcode project in /flutter-desktop-embedding/macos/example and click 'run', the window that pops up is blank, and the debug console gives me these errors:
```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
[ERROR:flutter/shell/platform/embedder/embedder_engine.cc(65)] Could not launch the engine with configuration.
flutter: Observatory listening on http://127.0.0.1:50803/
```

Thanks,
- Dave Sweeris

**Comment by gedw99** [comment] 2018-05-04 03:38
what versions are you on ?

For example
```
Flutter Version: abcdefg123456
Flutter Engine:  2345678qwertyu
```
Topaz had some changes recently and so that could be it.

**Comment by stuartmorgan** [comment] 2018-05-04 15:47
The instructions are written with the assumption that you have a project for a native application and want to incorporate Flutter into it. That's the application you would link the library into, not a Flutter application. I'm going to close this as a duplicate of issue #48, which is for supporting the workflow I'm pretty sure from your description is what you want.

The error you listen is unrelated to your question; the example app already links the framework. Please open a new issue for that, with your tree hashes.

**Closed by stuartmorgan** 2018-05-04 15:47 UTC

**Comment by TheOtherDave** [comment] 2018-05-04 15:55
Ah, ok. Thanks! I was pretty sure I was missing something like that.
