### ISSUE TITLE
compile with c++ cli

### ISSUE THREAD

**Issue by aasirmutwalli22** [google/flutter-desktop-embedding#780] opened 2020-08-05 11:37 UTC
I am building usb serial plugin for windows desktop. Hence clr flag is added in cmake. But application stops while running while bellow error. 

`Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at flutter.internal.ReplyManager.SendResponseData(ReplyManager* , vector<unsigned char\,std::allocator<unsigned char> >* )
   at flutter.EngineMethodResult<flutter::EncodableValue>.SuccessInternal(EngineMethodResult<flutter::EncodableValue>* , EncodableValue* result) in G:\documents\projects_mine\projects_mine\project_flutter_desktop_plugins\usb_serial\example\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\engine_method_result.h:line 61
   at flutter.MethodResult<flutter::EncodableValue>.Success(MethodResult<flutter::EncodableValue>* , EncodableValue* result) in G:\documents\projects_mine\projects_mine\project_flutter_desktop_plugins\usb_serial\example\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\method_result.h:line 27
   at ?A0xcb91bce5.UsbSerialPlugin.HandleMethodCall(UsbSerialPlugin* , MethodCall<flutter::EncodableValue>* method_call, unique_ptr<flutter::MethodResult<flutter::EncodableValue>\,std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >* result) in G:\documents\projects_mine\projects_mine\project_flutter_desktop_plugins\usb_serial\example\windows\flutter\ephemeral\.plugin_symlinks\usb_serial\windows\usb_serial_plugin.cpp:line 79
   at ?A0xcb91bce5.UsbSerialPlugin.RegisterWithRegistrar.<lambda_71f68a25f5c2dcc9e054a2e2a132a046>.operator()<class flutter::MethodCall<class flutter::EncodableValue>,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > > >(<lambda_71f68a25f5c2dcc9e054a2e2a132a046>* , MethodCall<flutter::EncodableValue>* call, unique_ptr<flutter::MethodResult<flutter::EncodableValue>\,std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >* result) in G:\documents\projects_mine\projects_mine\project_flutter_desktop_plugins\usb_serial\example\windows\flutter\ephemeral\.plugin_symlinks\usb_serial\windows\usb_serial_plugin.cpp:line 45
   at std._Invoker_functor._Call<class <lambda_71f68a25f5c2dcc9e054a2e2a132a046> &,class flutter::MethodCall<class flutter::EncodableValue> const &,class std::unique_ptr<class flutter::MethodResult<class flutter::EncodableValue>,struct std::default_delete<class flutter::MethodResult<class flutter::EncodableValue> > > >(<lambda_71f68a25f5c2dcc9e054a2e2a132a046>* _Obj, MethodCall<flutter::EncodableValue>* <_Args_0>, unique_ptr<flutter::MethodResult<flutter::EncodableValue>\,std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >* <_Args_1>) in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\type_traits:line 1612
   at std._Func_class<void,flutter::MethodCall<flutter::EncodableValue> const &,std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>,std::default_delete<flutter::MethodResult<flutter::EncodableValue> > > >.()(_Func_class<void\,flutter::MethodCall<flutter::EncodableValue> const \&\,std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>\,std::default_delete<flutter::MethodResult<flutter::EncodableValue> > > >* , MethodCall<flutter::EncodableValue>* <_Args_0>, unique_ptr<flutter::MethodResult<flutter::EncodableValue>\,std::default_delete<flutter::MethodResult<flutter::EncodableValue> > >* <_Args_1>) in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\functional:line 958
   at flutter.MethodChannel<flutter::EncodableValue>.SetMethodCallHandler.<lambda_a29ac0f81dffbce7aa22c0775df3194c>.()(<lambda_a29ac0f81dffbce7aa22c0775df3194c>* , Byte* message, UInt64 message_size, function<void __cdecl(unsigned char const \*\,unsigned __int64)>* reply) in G:\documents\projects_mine\projects_mine\project_flutter_desktop_plugins\usb_serial\example\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\method_channel.h:line 117
   at std._Invoker_functor._Call<class <lambda_a29ac0f81dffbce7aa22c0775df3194c> &,unsigned char const *,unsigned __int64,class std::function<void __cdecl(unsigned char const *,unsigned __int64)> >(<lambda_a29ac0f81dffbce7aa22c0775df3194c>* _Obj, Byte** <_Args_0>, UInt64* <_Args_1>, function<void __cdecl(unsigned char const \*\,unsigned __int64)>* <_Args_2>) in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\type_traits:line 1612
Waiting for Windows to report its views...
Debug service listening on ws://127.0.0.1:54205/nsSFCqSbbas=/ws
Syncing files to device Windows...
Lost connection to device.
`

**Comment by stuartmorgan** [comment] 2020-08-05 16:39
This is effectively a duplicate of https://github.com/google/flutter-desktop-embedding/issues/531, since this is the crash I reference in my July 6th comment there. I haven't yet had a chance to figure out what's causing it, but will update there when I do.

**Closed by stuartmorgan** 2020-08-05 16:39 UTC
