### ISSUE TITLE
How to disable window resize on Flutter Desktop Windows?

### ISSUE THREAD

**Issue by atfa** [google/flutter-desktop-embedding#729] opened 2020-05-16 06:23 UTC
When our Flutter desktop app running on Windows, if we resize the window or max the window, there will be a black area in the app. How to disable window resize on Flutter desktop windows?

I have tired

```
  ws.setWindowMaxSize(Size(width * 0.9, height * 0.9));
  ws.setWindowMinSize(Size(width * 0.9, height * 0.9));
```

But it does not work. There is no code to deal with the code 'setWindowMaxSize' and 'setWindowMinSize' in flutter-desktop-embedding\plugins\window_size\windows\window_size_plugin.cpp .

If it is difficult, is there any good idea to make the Flutter desktop app looks better when resizing? Maybe show a 'Loading' message? Thanks.

**Comment by stuartmorgan** [comment] 2020-05-16 15:40
Duplicate of https://github.com/google/flutter-desktop-embedding/issues/483

The black area you are describing sounds like https://github.com/flutter/flutter/issues/40068, which is just a bug in the embedding. The solution to that is to wait for it to be fixed; there's no need to add special code for it.

**Closed by stuartmorgan** 2020-05-16 15:40 UTC
