### ISSUE TITLE
[windows] app crashes after a hot restart

### ISSUE THREAD

**Issue by phanirithvij** [google/flutter-desktop-embedding#567] opened 2019-09-19 05:39 UTC
**Describe the bug**
Windows app crashes immediately after doing a hot restart with `R` key from the cli `flutter run` `To hot restart (and rebuild state), press "R"`.
For the example application provided here with no changes in dart code.

**Doctor Output**
the output of `flutter doctor -v`:
```
[√] Flutter (Channel master, v1.10.5-pre.15, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.10.5-pre.15 at D:\Software\flutter\flutterm
    • Framework revision fa9b376496 (13 hours ago), 2019-09-19 00:30:41 -0400
    • Engine revision eed16d34bd
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 cb80ea7ba9)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Rithvij\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.2.29306.81

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Rithvij\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18362.356]

• No issues found!
```

**Comment by phanirithvij** [comment] 2019-09-19 05:42
The error is `An unhandled win32 exception occurred in [18632] Flutter Destop Example.exe`

```
Unhandled exception at 0x00007FF86763A181 (flutter_windows.dll) in Flutter Desktop Example.exe: Fatal program exit requested. occurred
```

**Comment by stuartmorgan** [comment] 2019-09-19 05:51
Duplicate of https://github.com/flutter/flutter/issues/40070

**Closed by stuartmorgan** 2019-09-19 05:51 UTC
