### ISSUE TITLE
MissingPluginException (windows)

### ISSUE THREAD

**Issue by GreenTigerEye** [google/flutter-desktop-embedding#317] opened 2019-04-03 16:22 UTC
> [ERROR:c:\b\s\w\ir\k\src\flutter\lib\ui\ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method FileChooser.Show.Open on channel flutter/filechooser)

I get the following error when I use the default example project, while I try to click the button "Open" or "Save".

Did I miss something? I didn't understand the things described for the linking which was described here: https://github.com/google/flutter-desktop-embedding/blob/master/library/README.md 
Is this causing the error? If it is the case what do I have to do to fix it?

> The build results will be in the top-level out\ directory. You will need to link libflutter_embedder.dll and libflutter_engine.dll into your binary. Public headers will be in out/include/; you should point dependent builds at that location rather than the include/ directories in the source tree.

**Comment by canewsin** [comment] 2019-04-03 16:32
@GreenTigerEye 
> Example Application

> See the example application under each platform's directory in the example directory to see an example of including optional plugins on that platform. (The Windows example does not yet include any plugins, but the registration process would be the same as for Linux.)

above is from official docs plugin support is limited for now on windows
If you want to use precompiled binaries i had compiled here
you dont have to compile it from source use that instead
https://github.com/canewsin/flutter_desktop_launcher

**Comment by stuartmorgan** [comment] 2019-04-03 16:46
Yes, the plugin doesn't yet exist on Windows, per #105 (closing as a dup of that).

Arguably we should hide those buttons on Windows, but since it's just a test/example app, polish isn't a primary concern.

**Closed by stuartmorgan** 2019-04-03 16:46 UTC

**Comment by rlimaeco** [comment] 2020-02-24 01:00
No update yet ? That's so sad for desktop app on windows :/

**Comment by stuartmorgan** [comment] 2020-02-24 03:05
@rlimaeco See #105, which this was closed as a duplicate of. You'll see there that this plugin has been implemented for Windows now.
