### ISSUE TITLE
example exits without any error

### ISSUE THREAD

**Issue by rezaxdi** [google/flutter-desktop-embedding#240] opened 2019-01-20 23:37 UTC
Hi everyone,

I can build the example successfully on ubuntu 18.04 but when I try to run it just exits immediately without any error. Has anyone faced the same situation ?

**Comment by CallumIddon** [comment] 2019-01-20 23:40
Yes, I am currently investigating this issue. What is the hash of your Flutter clone?

**Comment by stuartmorgan** [comment] 2019-01-21 02:08
The GLFW implementation has some error paths that didn't end up with any logging, so it could be a failure there (e.g., GLFW window creation). A good starting point in debugging would be to add logging to the early returns in the example embedder and the GLFW embedder.cc (which I won't be able to get to myself for a couple of days, but would be happy to take a PR for).

**Comment by CallumIddon** [comment] 2019-01-21 02:15
That's what I was thinking of doing, just haven't gotten around to it yet. I know it has something to do with the Flutter clone as I experience this problem only some channels and not others.

**Comment by HazyFish** [comment] 2019-01-21 02:59
Same problem on Windows 10

**Comment by encombhat** [comment] 2019-01-21 03:02
Can be produced in Arch Linux.

In line 75 of https://github.com/google/flutter-desktop-embedding/blob/master/example/linux/flutter_embedder_example.cc#L75 , the GLFW window created is nullptr, and the code exited with error code 1.

**Comment by stuartmorgan** [comment] 2019-01-21 03:03
For anyone seeing this, please provide:
- The hash of your Flutter tree.
- Whether you've previously had the example working on your machine.

**Comment by stuartmorgan** [comment] 2019-01-21 03:06
> In line 75 of https://github.com/google/flutter-desktop-embedding/blob/master/example/linux/flutter_embedder_example.cc#L75 , the GLFW window created is nullptr, and the code exited with error code 1.

In CreateFlutterWindow, is the null return coming from `glfwCreateWindow`, or `RunFlutterEngine` (I would guess the latter given CallumIddon's comment above). If the latter, what is the `result` in the `FlutterEngineRun` error handling?

**Comment by encombhat** [comment] 2019-01-21 03:08
Well, flutter engine.version is 7375a0f414bde4bc941e623482221db2fc8c4ab5.
flutter-desktop-embedding commit is 1d90f970e94f1a0913c39de4449711addcb0b09e.
I can confirm commit f490eb6fdac3ffcb5716540e8864bbcc2d7abcfd is working.

**Comment by HazyFish** [comment] 2019-01-21 03:08
![image](https://user-images.githubusercontent.com/28922700/51450730-d0e73e80-1d6c-11e9-8f2a-521ea6472156.png)

**Comment by encombhat** [comment] 2019-01-21 03:10
> > In line 75 of https://github.com/google/flutter-desktop-embedding/blob/master/example/linux/flutter_embedder_example.cc#L75 , the GLFW window created is nullptr, and the code exited with error code 1.
> 
> In CreateFlutterWindow, is the null return coming from `glfwCreateWindow`, or `RunFlutterEngine` (I would guess the latter given CallumIddon's comment above). If the latter, what is the `result` in the `FlutterEngineRun` error handling?

It's from flutter_desktop_embedding::CreateFlutterWindowInSnapshotMode, the code exited at line 79.

**Comment by stuartmorgan** [comment] 2019-01-21 03:22
> flutter-desktop-embedding commit is 1d90f97.
I can confirm commit f490eb6 is working.

Ah, if this is a regression due to FDE changes, then 3089a8b0aed02083467ab6c381fa01d3a01cdc81 is almost certainly the culprit in that range.

> It's from flutter_desktop_embedding::CreateFlutterWindowInSnapshotMode, the code exited at line 79.

1d90f97 doesn't have CreateFlutterWindowInSnapshotMode, since it was renamed in 3089a8b0aed02083467ab6c381fa01d3a01cdc81. I've occasionally seen stale library issues with both Linux (Make, not GN) and Windows, that haven't been tracked down yet, so if everyone seeing this previously had working builds it may just be that something isn't being rebuilt.

Does doing a clean build (specifically, deleting all `.so`s from the tree on Linux--`make clean` may or may not get everything, since it hasn't been audited in a while) fix it?

**Comment by CallumIddon** [comment] 2019-01-22 02:53
All of these tests were done on Ubuntu 18.04.1 with a fresh clone of Flutter and FDE, using commit f26ec2e3c67aa83d83738a7410150d86f2d60b89 and built using Make (ninja behaved the same when I was playing around with it earlier). This issue is a side effect of 3089a8b0aed02083467ab6c381fa01d3a01cdc81 and everything before this commit works fine.

| Flutter Hash                                                            | Flutter Branch | Build Successful | Run Successful |
| :----------------------------------------------------------------- | :------------------ | :--------------------- | :-------------------- |
| 2eee7b7e942f57cb76075bed5fda8e1a619e5295  | master             | Yes                     | Yes                    |
| 1407091bfb5bb535630d4d596541817737da8412 | dev                  | Yes                     | Yes                    |
| 5391447fae6209bb21a89e6a5a6583cac1af9b4b  | beta/stable      | Yes                      | **No**               |

**Comment by stuartmorgan** [comment] 2019-01-22 04:08
I see what happened; prior to https://github.com/flutter/engine/pull/6973 the engine was erroring out if `main_path` and `packages_path` were null, even though snapshot mode didn't actually use them. It turns out that landed slightly after Flutter's stable branch landed.

Since passing a non-null value would log warnings with master/dev, there's no way to cleanly support both stable and master (and the code to pass something other than null in a way that would compile in against either version would be ugly, since the fields were renamed). So this falls under https://github.com/google/flutter-desktop-embedding/tree/master/library#caveats, and the solution is to use something newer than Flutter stable with current versions of FDE.

Closing, since #241 is already tracking making this failure less mysterious.

**Closed** 2019-01-22 04:09 UTC
