### ISSUE TITLE
[MacOS] stdout is not shown on Debug Console

### ISSUE THREAD

**Issue by putraxor** [google/flutter-desktop-embedding#249] opened 2019-01-26 12:27 UTC
stdout from `print` or `debugPrint` is not shown on debug console but shown on Dart VM Observatory debugger.

<img width="1680" alt="screen shot 2019-01-26 at 19 20 33" src="https://user-images.githubusercontent.com/6225082/51787068-b31c3e00-219f-11e9-8816-5a8b65f11e9a.png">

## Version
```
    • Flutter version 1.0.0 at /Users/putraxor/Dev/flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

**Comment by stuartmorgan** [comment] 2019-01-26 14:11
How did you run the application? Unless you have a custom run command configured in VS Code so that it actually launched the process, there's no reason that stdout would go there.

**Comment by putraxor** [comment] 2019-01-27 22:33
Just ran the runtime app and attached to Visual Studio Code.
I thought that the debug console output came from observatory debugger

**Comment by stuartmorgan** [comment] 2019-01-27 23:49
The way you launched the app controls where stdout goes. If you want stdout in VS Code, you need to launch your application from VS Code.

Closing, since this is normal behavior, not a bug.

**Closed by stuartmorgan** 2019-01-27 23:49 UTC

**Comment by jacobaraujo7** [comment] 2019-04-23 20:25
here also no stdout appears in the vscode debug console. If I wanted to see the prints I would have to go to the Observatory

**Comment by stuartmorgan** [comment] 2019-04-23 20:51
If you are launching separately and attaching, then that's expected behavior as described above.

If you are running directly from within VS Code using the new workflow, please file a new bug, because that's not what this bug was about.

**Comment by stuartmorgan** [comment] 2019-04-23 21:05
I see this with the new workflow. Filed https://github.com/flutter/flutter/issues/31521 since the problem is at the flutter_tool level, not the IDE; follow there for updates.

**Comment by tttzof351** [comment] 2019-05-03 03:47
On Linux debugPrint not showing in flutter logs (expected behavior according to https://api.flutter.dev/flutter/foundation/debugPrint.html)

I am trying:
- append debugPrint("test") on pressed callback
- run app through flutter run
- run logs through flutter logs
- click by button

**Comment by stuartmorgan** [comment] 2019-05-03 13:18
`flutter logs` is not implemented for desktop. Printed messages will be in the console output of `flutter run`.

**Comment by tttzof351** [comment] 2019-05-03 15:11
> `flutter logs` is not implemented for desktop. Printed messages will be in the console output of `flutter run`.

I can't see result of debugPrint or print in console, where I call flatter run, also I can't see result and in stdout of testbed process (`tail -f /proc/`pgrep testbed`/fd/1`)

Devtools also not working - when I am trying connected by port (after `flutter run --observatory-port=9200`), I see "Unable to connect" :(

**Comment by stuartmorgan** [comment] 2019-05-03 18:04
This is getting off-topic for this issue; which was never about the `flutter run` workflow in the first place. Please file new issues:
- One for the stdout issue, after you've verified that you are using the latest version of Flutter master (and thus have the fix for https://github.com/flutter/flutter/issues/31521)
- One for the connection issue, after making sure that you've read the updated version of Debugging.md and are taking the new auth token in the URL into account in your workflow.
