### ISSUE TITLE
Page doesn't fit in the screen when maximized or minimized on windows

### ISSUE THREAD

**Issue by aneeshjose** [google/flutter-desktop-embedding#612] opened 2019-11-23 06:36 UTC
**Describe the bug**
The pages behaves weird  when maximized or minimized on windows

Screenshots:

![Screenshot (76)](https://user-images.githubusercontent.com/31209870/69474595-2c4ce780-0de9-11ea-96b8-d45b4131e20e.png)

when maximized :

![Screenshot (77)](https://user-images.githubusercontent.com/31209870/69474598-3b339a00-0de9-11ea-9a23-80c5bc01cab7.png)

When minimized back

![Screenshot (78)](https://user-images.githubusercontent.com/31209870/69474623-6322fd80-0de9-11ea-863c-d090dd4baa15.png)

**Doctor Output**
Please provide the output of `flutter doctor -v`:
```
[√] Flutter (Channel master, v1.10.15-pre.186, on Microsoft Windows [Version 10.0.17134.523], locale en-IN)
    • Flutter version 1.10.15-pre.186 at C:\src\flutterweb\flutter
    • Framework revision 1c535de7e0 (5 weeks ago), 2019-10-18 16:40:42 -0700
    • Engine revision 8aefcd8575
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Aneesh\AppData\Local\Android\Sdk\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.3.29519.87

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at F:\intellij Idea\IntelliJ IDEA Community Edition 2017.3.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.39.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.17134.523]
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

```

**Comment by stuartmorgan** [comment] 2019-11-23 09:36
Duplicate of https://github.com/flutter/flutter/issues/40068

**Closed by stuartmorgan** 2019-11-23 09:36 UTC
