### ISSUE TITLE
[Linux] Compiling the embedder requires libjsoncpp.so.1, but it doesn't exist on Fedora 29

### ISSUE THREAD

**Issue by sr229** [google/flutter-desktop-embedding#227] opened 2019-01-11 12:19 UTC
Compiling the embedder throws in the following:

```
[asatomi@mirai Mariya]$ ./target/out/linux/alcantara
./target/out/linux/alcantara: error while loading shared libraries: libjsoncpp.so.1: cannot open shared object file: No such file or directory
```
Running `ldd` throws in the following (ls of `/usr/lib64` included).

```
[asatomi@mirai Mariya]$ ls /usr/lib64 | grep libjsoncpp
libjsoncpp.so
libjsoncpp.so.1.8.4
libjsoncpp.so.19
[asatomi@mirai Mariya]$ ldd ./target/out/linux/alcantara | grep libjsoncpp
        libjsoncpp.so.19 => /lib64/libjsoncpp.so.19 (0x00007f382d605000)
        libjsoncpp.so.1 => not found
[asatomi@mirai Mariya]$
```

**Comment by sr229** [comment] 2019-01-11 12:20
Workaround is to install the Magiea RPM in [RPMFind](https://rpmfind.net/linux/rpm2html/search.php?query=libjsoncpp.so.1()(64bit))

**Comment by stuartmorgan** [comment] 2019-01-11 15:30
The [README for the library](https://github.com/google/flutter-desktop-embedding/blob/master/library/README.md) lists jsoncpp as one of the dependencies you need to install; build failures are expected if you are missing required dependencies.

Closing, as this is already a documented requirement, so not a bug.

(However, I would accept a patch to make the Linux GN build have an option to build jsoncpp from source, as we do on Windows, if someone is interested in providing that as an alternative to a distribution-level install of jsoncpp.)

**Closed by stuartmorgan** 2019-01-11 15:30 UTC
