### ISSUE TITLE
Observatory can't see source code of dart:ui

### ISSUE THREAD

**Issue by sodapanda** [google/flutter-desktop-embedding#154] opened 2018-11-18 13:39 UTC
![image](https://user-images.githubusercontent.com/620479/48673212-2428ef00-eb7a-11e8-828d-5e0295b69106.png)

Observatory can't see source code of dart:ui.
Can I debug dart:ui source code in Observatory?

Flutter source code version: v0.11.6
engine version:114d33d3caa24d260f15529e1f3f50783cbccd9a

**Comment by stuartmorgan** [comment] 2018-11-18 20:38
I'm not familiar enough with the VM internals to know whether this is expected behavior for our build configuration. It may be that you need to build a Debug version of the engine, for instance, to debug frameworks.

I'll test with a local engine build when I get a chance; if that's not we'll need to talk to someone who knows more about how the debugging data is managed for Flutter frameworks.

**Comment by sodapanda** [comment] 2018-11-20 11:50
@stuartmorgan 

[https://github.com/dart-lang/sdk/issues/34666#issue-366510558](url)

It looks like a bug of the Dart VM

**Comment by stuartmorgan** [comment] 2018-11-20 13:11
Since it's not specific to desktop embedding, closing.

**Closed by stuartmorgan** 2018-11-20 13:11 UTC
