### ISSUE TITLE
font-related segmentation fault 

### ISSUE THREAD

**Issue by pmatteo1998** [google/flutter-desktop-embedding#59] opened 2018-05-22 05:08 UTC
this code section:

new TextField(style: TextStyle(fontSize: 10.01),);

triggers a sigfault. 
passing a POC through gdb i've found this message error:

Thread 2 "io.flutter.ui" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffXXXXXXXX (LWP 10286)]
minikin::FontCollection::baseFontFaked (this=0x0, style=...)
    at ../../flutter/third_party/txt/src/minikin/FontCollection.cpp:506   ../../flutter/third_party/txt/src/minikin/FontCollection.cpp: No such file or directory.

**Comment by pmatteo1998** [comment] 2018-05-22 06:01
i've found a workaround :  
TextStyle(fontSize: 10.01,fontFamily: "Roboto") 
 
i'm starting that to think that engine works with a "default" family that come packed with os (android or os x) and don't check if that is present in the system, even in the embedded version.

**Comment by stuartmorgan** [comment] 2018-05-22 06:01
Again, we need your tree hashes. If you are going to be filing bugs, please follow the reporting instructions in the README:
https://github.com/google/flutter-desktop-embedding#discussion
We have no way of trying to reproduce your bugs without this information.

Is this on Linux as well?

**Comment by pmatteo1998** [comment] 2018-05-22 06:10
flutter:c169136effe913693a5d31f0b9b97cce53a6a1df
engine:06afdfe54ebef9168a90ca00a6721c2d36e6aafa

**Comment by pmatteo1998** [comment] 2018-05-22 07:00
i used the example app code with the build method that returns:

new Scaffold(body:new TextField(style: TextStyle(fontSize: 10.01,),);

**Comment by mikemaksymowych** [comment] 2018-07-02 20:44
Stuck on a similar (?) issue:

```Starting program: /opt/flutter-src/flutter-desktop-embedding/linux/example/flutter_embedder_example 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
---- failed to open </usr/share/fonts/truetype/noto/NotoColorEmoji.ttf> <0> as a font
flutter: Observatory listening on http://127.0.0.1:38825/

Thread 5 "io.flutter.ui" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd7d62700 (LWP 5439)]
0x00007ffff41bcd60 in minikin::FontCollection::baseFontFaked(minikin::FontStyle) () from /opt/flutter-src/flutter-desktop-embedding/linux/library/libflutter_engine.so
(gdb) bt
#0  0x00007ffff41bcd60 in minikin::FontCollection::baseFontFaked(minikin::FontStyle) () at /opt/flutter-src/flutter-desktop-embedding/linux/library/libflutter_engine.so
#1  0x00007ffff41d508c in txt::Paragraph::GetDefaultSkiaTypeface(txt::TextStyle const&) () at /opt/flutter-src/flutter-desktop-embedding/linux/library/libflutter_engine.so
#2  0x00007ffff41d2b70 in txt::Paragraph::Layout(double, bool) () at /opt/flutter-src/flutter-desktop-embedding/linux/library/libflutter_engine.so
#3  0x00007ffff41fe494 in blink::Paragraph_layout(_Dart_NativeArguments*) () at /opt/flutter-src/flutter-desktop-embedding/linux/library/libflutter_engine.so
#4  0x00007ffff4415f1c in dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) (args=0x7fffd7d5e2c0, func=0x7ffff41fe430 <blink::Paragraph_layout(_Dart_NativeArguments*)>) at ../../third_party/dart/runtime/vm/native_entry.cc:198
```

flutter-desktop-embedding: ```commit c6ce40c5863871087671368215d649f37703aa66 (HEAD -> master, origin/master, origin/HEAD)```

flutter: ```commit 647076d7679d9475c4f0be2a19c95aa53d1ed930 (HEAD -> master, origin/master, origin/HEAD)```

**Comment by stuartmorgan** [comment] 2018-07-02 22:23
For the original issue, I was never able to reproduce it, but hopefully PR #82 will help since it's setting the font explicitly. (Although I'm confused why adding fontFamily:Roboto would have helped since Roboto should be the default for Android, which is what Flutter uses as the target platform for Linux hosts).

For the most recent comment, I'm not sure what in the example app is trying to load an emoji. Is this just trying to launch the unmodified example app?

**Comment by mikemaksymowych** [comment] 2018-07-02 22:34
@stuartmorgan, yes, just trying to launch the provided example after `make`.

Stripping the example to bare bones, e.g. a single `Container` works, although the emoji error remains. So this font may not be the root cause of the crash, although minikin seems to imply the crash is still font related.

Thanks :)

**Comment by mikemaksymowych** [comment] 2018-07-05 23:12
#82 fixed my issues, although the emoji warning still shows

**Comment by stuartmorgan** [comment] 2018-07-09 22:38
That's tracked in #90; closing since the crash is apparently fixed.

**Closed by stuartmorgan** 2018-07-09 22:38 UTC
