### ISSUE TITLE
macOS code signing fails on empty /App.framework/Versions/A directory

### ISSUE THREAD

**Issue by GreenAppers** [google/flutter-desktop-embedding#487] opened 2019-08-16 21:07 UTC
It seems that the App.framework added here https://github.com/google/flutter-desktop-embedding/commit/cc4a7d8e78e56fc3581b6f5ca969b00ceb14b098 (and I think needed to build against flutter master) breaks code signing for derived apps.

I have an app derived from flutter-desktop-embedding that I want to sign and it was working a few days ago: https://github.com/GreenAppers/cruzall-macos

Then I got a build error about FLEViewController which I believe has been renamed.  I merged flutter-desktop-embedding and now the build succeeds but archive fails. 

It's trying to codesign an empty App.framework/Versions/A directory:
[        ]     /usr/bin/codesign --force --sign ...abbreviated... --timestamp=none /Users/travis/build/GreenAppers/cruzall-macos/cruzall/build/macos/Build/Products/Release/Cruzall.app/Contents/Frameworks/App.framework/Versions/A
[        ] /Users/travis/build/GreenAppers/cruzall-macos/cruzall/build/macos/Build/Products/Release/Cruzall.app/Contents/Frameworks/App.framework/Versions/A: bundle format unrecognized, invalid, or unsuitable
[        ] Command CodeSign failed with a nonzero exit code
[  +17 ms] ** BUILD FAILED **
(From: https://travis-ci.org/GreenAppers/cruzall-macos/builds/572899424 )

Steps to reproduce: Configure code signing for example app in XCode and then Product > Archive.

Expected behavior: Signed example app archive is produced. 

[✓] Flutter (Channel master, v1.9.1-pre.70, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 1.9.1-pre.70 at /Users/travis/flutter
    • Framework revision 0b087a898a (69 minutes ago), 2019-08-16 11:23:21 -0700
    • Engine revision 41eb729a65
    • Dart version 2.5.0 (build 2.5.0-dev.2.1 2023f09b56)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode-10.1.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.13.6 17G65
! Doctor found issues in 2 categories.

**Comment by stuartmorgan** [comment] 2019-08-17 01:37
The Framework currently isn't being built correctly by the `flutter` tool; filed https://github.com/flutter/flutter/issues/38728. I suspect that resolving that will be enough to fix signing, but I'll leave this open until that's confirmed in case there's anything else about the addition of the framework that causes issues.

(As usual when questions/bugs around "release" builds come up, I feel obligated to remind you that as the README says, this code *is not currently intended for release or production use*, and that the thing you are signing is, in reality, a debug build for all practical purposes.)

**Comment by GanZhiXiong** [comment] 2019-08-19 08:18
I have also encountered this problem. May I ask how to solve it?

**Comment by stuartmorgan** [comment] 2019-08-19 14:20
There is a work-in-progress PR linked from the referenced bug if you are interested in the details of the fix.

**Comment by stuartmorgan** [comment] 2019-08-20 17:58
Please let me know whether this is fully resolved after updating both projects to the latest master; if not, please post the new error message.

**Comment by GreenAppers** [comment] 2019-08-20 20:53
Cocoapods says "dependency were found, but they required a higher minimum deployment target." (https://travis-ci.org/GreenAppers/cruzall-macos/builds/574526622 )

Looks like the OSX deployment target was lowered to 10.11 for macos/Runner, but
my macos/Flutter/ephemeral/.symlinks/flutter/darwin-x64/FlutterMacOS.podspec has s.osx.deployment_target = '10.12'

If I change the deployment target to 10.12 in the macos/Runner project and the macos/Podfile the build succeeds.

However then codesign fails with a not-very-descriptive error:

/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app: code object is not signed at all
In subcomponent: /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app/Contents/Frameworks/App.framework
Command CodeSign failed with a nonzero exit code

bash-3.2$ flutter doctor -v
[✓] Flutter (Channel master, v1.9.2-pre.36, on Mac OS X 10.14.6 18G84, locale en-US)
    • Flutter version 1.9.2-pre.36 at /Users/jfoutts/flutter
    • Framework revision 28bedb10da (59 minutes ago), 2019-08-20 12:53:59 -0700
    • Engine revision d212b9ab33
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jfoutts/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.14.6 18G84

! Doctor found issues in 1 category.

**Comment by stuartmorgan** [comment] 2019-08-20 21:49
The deployment target is a known issue that will be fixed by [this PR](https://github.com/flutter/engine/pull/11306).

It's not clear to me offhand what the issue with signing the corrected framework is; that will need further investigation.

**Comment by GreenAppers** [comment] 2019-08-20 22:25
It seems the build doesn't attempt signing App.framework.  FlutterMacOS.framework and url_launcher_fde.framework are signed, then it goes straight to the app signing.  It fails because App.framework wasn't signed.

Log from my machine:
```
Showing Recent Messages
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target: Runner)
    cd /Users/jfoutts/cruzall-macos/cruzall/macos
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Cruzall -O -whole-module-optimization -enforce-exclusivity=checked -D COCOAPODS -D COCOAPODS -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -target x86_64-apple-macosx10.12 -g -module-cache-path /Users/jfoutts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -swift-version 4 -I /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release -F /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release -F /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release/url_launcher_fde -F /Users/jfoutts/cruzall-macos/cruzall/macos/Flutter/ephemeral/.symlinks/flutter/darwin-x64 -F /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release/url_launcher_fde -F /Users/jfoutts/cruzall-macos/cruzall/macos/Flutter/ephemeral/.symlinks/flutter/darwin-x64 -F /Users/jfoutts/cruzall-macos/cruzall/macos/Flutter/ephemeral -c -num-threads 8 /Users/jfoutts/cruzall-macos/cruzall/macos/ExampleWindow.swift /Users/jfoutts/cruzall-macos/cruzall/macos/AppDelegate.swift /Users/jfoutts/cruzall-macos/cruzall/macos/Flutter/GeneratedPluginRegistrant.swift -output-file-map /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/Objects-normal/x86_64/Runner-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/Objects-normal/x86_64/Cruzall.swiftmodule -Xcc -I/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/Cruzall-generated-files.hmap -Xcc -I/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/Cruzall-own-target-headers.hmap -Xcc -I/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/Cruzall-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/Cruzall-project-headers.hmap -Xcc -I/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release/include -Xcc -I/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release/url_launcher_fde/url_launcher_fde.framework/Headers -Xcc -I/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release/url_launcher_fde/url_launcher_fde.framework/Headers -Xcc -I/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/DerivedSources-normal/x86_64 -Xcc -I/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/DerivedSources -Xcc -DCOCOAPODS=1 -Xcc -DCOCOAPODS=1 -emit-objc-header -emit-objc-header-path /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/Objects-normal/x86_64/Cruzall-Swift.h -working-directory /Users/jfoutts/cruzall-macos/cruzall/macos

PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/Script-BB6F24D4D078B821A80100B7.sh (in target: Runner)
    cd /Users/jfoutts/cruzall-macos/cruzall/macos
    /bin/sh -c /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/Script-BB6F24D4D078B821A80100B7.sh

mkdir -p /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release/Cruzall.app/Contents/Frameworks
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/jfoutts/cruzall-macos/cruzall/macos/Pods/../Flutter/ephemeral/.symlinks/flutter/darwin-x64/FlutterMacOS.framework" "/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app/Contents/Frameworks"
building file list ... done
deleting FlutterMacOS.framework/Versions/A/_CodeSignature/CodeResources
deleting FlutterMacOS.framework/Versions/A/_CodeSignature/
FlutterMacOS.framework/
FlutterMacOS.framework/Versions/
FlutterMacOS.framework/Versions/A/
FlutterMacOS.framework/Versions/A/FlutterMacOS
FlutterMacOS.framework/Versions/A/Resources/
FlutterMacOS.framework/Versions/A/Resources/Info.plist
FlutterMacOS.framework/Versions/A/Resources/icudtl.dat

sent 35908793 bytes  received 110 bytes  71817806.00 bytes/sec
total size is 35903941  speedup is 1.00
Destination binary is symlinked...
Code Signing /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app/Contents/Frameworks/FlutterMacOS.framework with Identity Developer ID Application: Lucid Fusion Labs, LLC (******)
/usr/bin/codesign --force --sign ******  --preserve-metadata=identifier,entitlements '/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app/Contents/Frameworks/FlutterMacOS.framework'
Symlinked...
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/macosx/url_launcher_fde.framework" "/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app/Contents/Frameworks"
building file list ... done
url_launcher_fde.framework/
url_launcher_fde.framework/Resources -> Versions/Current/Resources
url_launcher_fde.framework/url_launcher_fde -> Versions/Current/url_launcher_fde
url_launcher_fde.framework/Versions/
url_launcher_fde.framework/Versions/Current -> A
url_launcher_fde.framework/Versions/A/
url_launcher_fde.framework/Versions/A/url_launcher_fde
url_launcher_fde.framework/Versions/A/Resources/
url_launcher_fde.framework/Versions/A/Resources/Info.plist

sent 38507 bytes  received 106 bytes  77226.00 bytes/sec
total size is 38052  speedup is 0.99
Destination binary is symlinked...
Code Signing /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app/Contents/Frameworks/url_launcher_fde.framework with Identity Developer ID Application: Lucid Fusion Labs, LLC (******)
/usr/bin/codesign --force --sign ******  --preserve-metadata=identifier,entitlements '/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app/Contents/Frameworks/url_launcher_fde.framework'

CodeSign /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app (in target: Runner)
    cd /Users/jfoutts/cruzall-macos/cruzall/macos
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "Developer ID Application: Lucid Fusion Labs, LLC (*********)"

    /usr/bin/codesign --force --sign ****** --entitlements /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/Runner.build/Cruzall.app.xcent --requirements =designated\ =\>\ anchor\ apple\ generic\ \ and\ identifier\ \"\$self.identifier\"\ and\ \(\(cert\ leaf\[field.1.2.840.113635.100.6.1.9\]\ exists\)\ or\ \(\ certificate\ 1\[field.1.2.840.113635.100.6.2.6\]\ exists\ and\ certificate\ leaf\[field.1.2.840.113635.100.6.1.13\]\ exists\ \ and\ certificate\ leaf\[subject.OU\]\ =\ \"**********\"\ \)\) /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app

/Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app: code object is not signed at all
In subcomponent: /Users/jfoutts/Library/Developer/Xcode/DerivedData/Runner-auozvyxescuhcqahthimwgurqvnc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Cruzall.app/Contents/Frameworks/App.framework
Command CodeSign failed with a nonzero exit code
```

**Comment by stuartmorgan** [comment] 2019-08-20 23:00
Which is strange given that "Sign On Copy" is enabled in the bundle step, just as with FlutterMacOS.framework.

**Comment by GanZhiXiong** [comment] 2019-08-21 07:43
Is it the latest version of flutter master? I remember that I didn't update the flutter before it was available for use

**Comment by GreenAppers** [comment] 2019-08-21 17:22
Looks like the problem is that the symlinks in App.framework are to absolute file paths instead of relative.

I can successfully run codesign on the FlutterMacOS.framework in macos/Flutter/ephemeral but on App.framework it errors with:
unsealed contents present in the root directory of an embedded framework

However if I replace the App, Resources, and Versions/Client in App.framework with relative symlinks it works!

P.S. I noticed that it's picky about the symlinks.  Linking Resources to Versions/Current/Resources/ (note the trailing slash) still produces the error.  Only linking to exactly Versions/Current/Resources works.

**Comment by stuartmorgan** [comment] 2019-08-21 17:25
Ah, good find. I had looked to see if the symlinks were being flattened on copy or something along those lines, but missed that the paths were odd.

**Comment by stuartmorgan** [comment] 2019-08-23 20:28
The latest changes (which also add Release mode support for macOS) should really fix this; Jonah verified that he was able to sign locally. Please comment if you still have issues after updating again.

**Closed by stuartmorgan** 2019-08-23 20:28 UTC
Labels: bug
