### ISSUE TITLE
vswhere doesn't find Build Tools when the Visual Studio IDE not installed

### ISSUE THREAD

**Issue by metaa** [google/flutter-desktop-embedding#585] opened 2019-10-05 01:03 UTC
**Describe the bug**
`flutter doctor` doesn't find VS Build Tools when the Visual Studio IDE is not installed.
See [this comment](https://github.com/Microsoft/vswhere/issues/103#issuecomment-330567014).

**Doctor Output**
```
[√] Flutter (Channel master, v1.10.7-pre.109, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.10.7-pre.109 at Y:\dev\Flutter\sdk
    • Framework revision 056f7244ef (3 days ago), 2019-10-01 18:09:24 -0400
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.4.0 1103600280)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at Y:\dev\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: Y:\Software\JetBrains\apps\AndroidStudio\ch-0\191.5900203\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including following components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools
       - If there are multiple versions, install the latest one
        Windows 10 SDK (10.0.17763.0)

[√] Android Studio (version 3.5)
    • Android Studio at Y:\Software\JetBrains\apps\AndroidStudio\ch-0\191.5900203
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18362.356]

! Doctor found issues in 1 category.
```

**Results of my research**
According to the comment linked above, the `vswhere` binary doesn't find standalone installations of the build tools. Adding `-products *` to the commands seems to solve this.

One of [the commands](visual_studio.dart) `flutter doctor` runs:
```cmd
vswhere.exe -format json -utf8 -latest -prerelease -all
```
**Output**:
```json
[]
```

Fixed:
```cmd
vswhere.exe -format json -utf8 -latest -prerelease -products *
```
**Output**:
```json
[
  {
    "instanceId": "d986cc10",
    "installDate": "2019-10-05T00:00:21Z",
    "installationName": "VisualStudio/16.3.2+29326.143",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools",
    "installationVersion": "16.3.29326.143",
    "productId": "Microsoft.VisualStudio.Product.BuildTools",
    "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\Common7\\Tools\\LaunchDevCmd.bat",
    "state": 4294967295,
    "isComplete": true,
    "isLaunchable": true,
    "isPrerelease": false,
    "isRebootRequired": false,
    "displayName": "Visual Studio Build Tools 2019",
    "description": "The Visual Studio Build Tools allows you to build native and managed MSBuild-based applications without requiring the Visual Studio IDE. There are options to install the Visual C++ compilers and libraries, MFC, ATL, and C++/CLI support.",
    "channelId": "VisualStudio.16.Release",
    "channelUri": "https://aka.ms/vs/16/release/channel",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.3.2",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
    "updateDate": "2019-10-05T00:00:21.8334269Z",
    "catalog": {
      "buildBranch": "d16.3",
      "buildVersion": "16.3.29326.143",
      "id": "VisualStudio/16.3.2+29326.143",
      "localBuild": "build-lab",
      "manifestName": "VisualStudio",
      "manifestType": "installer",
      "productDisplayVersion": "16.3.2",
      "productLine": "Dev16",
      "productLineVersion": "2019",
      "productMilestone": "RTW",
      "productMilestoneIsPreRelease": "False",
      "productName": "Visual Studio",
      "productPatchVersion": "2",
      "productPreReleaseMilestoneSuffix": "1.0",
      "productSemanticVersion": "16.3.2+29326.143",
      "requiredEngineVersion": "2.3.2276.2797"
    },
    "properties": {
      "campaignId": "",
      "channelManifestId": "VisualStudio.16.Release/16.3.2+29326.143",
      "nickname": "",
      "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
    }
  }
]
```

**Comment by metaa** [comment] 2019-10-05 01:39
I replaced `vswhere.exe` with a custom binary that adds `-products *` into the equation and now `flutter doctor` seems to be happy.

```
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.3.2)
```

**Comment by metaa** [comment] 2019-10-05 01:48
I updated the initial post according to reflect the actual problem according to the knowledge gained by researching this (and actually reading the linked comment word by word 😅)

**Comment by stuartmorgan** [comment] 2019-10-05 20:03
Duplicate of https://github.com/flutter/flutter/issues/39067

**Closed by stuartmorgan** 2019-10-05 20:03 UTC
