### ISSUE TITLE
[window_size] Window size cause GitHub timeout during  flutter pub get

### ISSUE THREAD

**Issue by winqoo** [google/flutter-desktop-embedding#905] opened 2022-07-19 06:58 UTC
### Is this a bug in one of the plugins in this project?

- [X] I have read [the README section about feedback](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback).
- [X] My issue is about one of the plugins in this repository.

### Which plugin is this bug report about?

window_size

### Describe the bug

I added  window_size to my pubspec.yaml 

```
window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
```
      
after running flutter pub get I keep getting GitHub timeout error.
     
     

> Git error. Command: `git clone --mirror git://github.com/google/flutter-desktop-embedding.git /Users/michalwinkler/development/flutter/.pub-cache/git/cache/flutter-desktop-embedding-87b62662532896a522efe2d4fc10c086d1a2768b`
> stdout: 
> stderr: Cloning into bare repository '/Users/user/development/flutter/.pub-cache/git/cache/flutter-desktop-embedding-87b62662532896a522efe2d4fc10c086d1a2768b'...
> fatal: unable to connect to github.com:
> github.com[0: 140.82.121.4]: errno=Operation timed out

I tested it on fresh flutter project with no other dependencies

### Flutter doctor

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-x64, locale
    en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by stuartmorgan** [comment] 2022-07-19 13:13
Duplicate of https://github.com/google/flutter-desktop-embedding/issues/900

**Closed by stuartmorgan** 2022-07-19 13:13 UTC
