### ISSUE TITLE
Feature Request: support webview , for mac osx

### ISSUE THREAD

**Issue by netroby** [google/flutter-desktop-embedding#693] opened 2020-03-15 07:18 UTC
I am tried build app with flutter desktop for mac, seems there no webview for flutter. 
I need to integrated with web page. call function and send data to render as webpage.

I am now can using electron build app contains webpage. but i want to using flutter desktp embedding framework to rewrite my apps. 
thanks.

**Comment by stuartmorgan** [comment] 2020-03-15 13:28
Duplicate of https://github.com/flutter/flutter/issues/41725

**Closed by stuartmorgan** 2020-03-15 13:28 UTC
