### ISSUE TITLE
PageView Minimize, then open and always show the first page

### ISSUE THREAD

**Issue by Slihao** [google/flutter-desktop-embedding#718] opened 2020-04-18 11:59 UTC
**Describe Request**

**Comment by Slihao** [comment] 2020-04-18 11:59
on Windows

**Comment by stuartmorgan** [comment] 2020-04-18 12:20
This doesn't sound like it's about any of the plugins in this repository, so closing; please read https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback

If this is related to a plugin, please provide sample code to reproduce it, and a clearer description, since I can't tell from the title some what your issue is.

**Closed by stuartmorgan** 2020-04-18 12:20 UTC

**Comment by Slihao** [comment] 2020-04-20 06:53
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        //visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: new PageView(
        children: [
          new Container(child: new Center(child:new Text("0")),),
          new Container(child: new Center(child:new Text("1")),),
          new Container(child: new Center(child:new Text("2")),),
        ],
      )// This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}



************************PageView控件****************************************
The above code works fine on the phone
but  On Windows
When the PageView slides to the second page, it is minimized and then opened. The PageView shows the first page

**Comment by Slihao** [comment] 2020-04-20 07:27
> This doesn't sound like it's about any of the plugins in this repository, so closing; please read https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback
> 
> If this is related to a plugin, please provide sample code to reproduce it, and a clearer description, since I can't tell from the title alone what your issue is.

import 'package:flutter/material.dart';

void main() {
runApp(MyApp());
}
class MyApp extends StatelessWidget {
// This widget is the root of your application.
@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Flutter Demo',
theme: ThemeData(
primarySwatch: Colors.blue,
//visualDensity: VisualDensity.adaptivePlatformDensity,
),
home: MyHomePage(title: 'Flutter Demo Home Page'),
);
}
}
class MyHomePage extends StatefulWidget {
MyHomePage({Key key, this.title}) : super(key: key);
final String title;
@override
_MyHomePageState createState() => _MyHomePageState();
}
class _MyHomePageState extends State {
@override
Widget build(BuildContext context) {
return Scaffold(
body: new PageView(
children: [
new Container(child: new Center(child:new Text("0")),),
new Container(child: new Center(child:new Text("1")),),
new Container(child: new Center(child:new Text("2")),),
],
)// This trailing comma makes auto-formatting nicer for build methods.
);
}
}

PageView控件****************
The above code works fine on the phone
but On Windows
When the PageView slides to the second page, it is minimized and then opened. The PageView shows the first page

**Comment by stuartmorgan** [comment] 2020-04-20 15:10
There is no plugin in the code you've posted. Please read the link I posted above; your issue report belongs in the Flutter repository, not here.
