### ISSUE TITLE
Avoiding resize on Linux

### ISSUE THREAD

**Issue by iyiola-dev** [google/flutter-desktop-embedding#795] opened 2020-09-10 02:48 UTC
**Describe Request**
How to make Linux apps not to resize

**Comment by stuartmorgan** [comment] 2020-09-10 04:37
This is exactly the same as https://github.com/google/flutter-desktop-embedding/issues/774.

Please search the open issues before filing new ones. (There are only 10, and the one this is a duplicate of is the first one on the list, so it would not have been hard to find.)

**Closed by stuartmorgan** 2020-09-10 04:37 UTC
