### ISSUE TITLE
Is RichText support cmd+c on desktop development? if yes, how can I implement it?

### ISSUE THREAD

**Issue by bing0ye** [google/flutter-desktop-embedding#697] opened 2020-03-19 03:10 UTC
Is RichText support cmd+c on desktop development? if yes, how can I implement it?

**Comment by stuartmorgan** [comment] 2020-03-19 03:44
Not yet. Duplicate of https://github.com/flutter/flutter/issues/23603

**Closed by stuartmorgan** 2020-03-19 03:44 UTC

**Comment by bing0ye** [comment] 2020-03-19 06:35
OK，I will follow it.
