### ISSUE TITLE
Dart dependency resolving fails

### ISSUE THREAD

**Issue by Schwusch** [google/flutter-desktop-embedding#4] opened 2018-02-25 12:13 UTC
When running a Swift desktop project on mac with the FlutterEmbedderMac.framework I get this message:

```
Observatory server failed to start after 1 tries
error: Unable to read Dart source 'package:flutter/material.dart'.
```
The dart files and `.packages` file is located in the xcode project.

```swift
flutterViewController = FLEViewController()
flutterViewController?.launchEngine(
    withMainPath: Bundle.main.url(forResource: "main", withExtension:"dart")!,
    assetsPath: URL.init(fileURLWithPath: ".", isDirectory: true),
    packagesPath: Bundle.main.url(forResource: ".packages", withExtension: nil)!,
    asHeadless: false,
    commandLineArguments: [])
```
The `.packages` file defines the Flutter package as such:
```
# Generated by pub on 2018-02-25 11:22:00.767792.
...
csslib:file:///Users/jonathan/.pub-cache/hosted/pub.dartlang.org/csslib-0.14.1/lib/
flutter:file:///Users/jonathan/flutter/packages/flutter/lib/
...
```
I've confirmed that the path and files exist.

**Comment by stuartmorgan** [comment] 2018-02-26 18:42
I'm not sure offhand what's causing this, but I'm working on putting together a simple example app to add to the repository, which should make it easier to get started (and help with debugging issues like this locally, by comparing to the working example). If I happen to encounter this while assembling the example and figure out the cause I'll update here.

**Comment by stuartmorgan** [comment] 2018-02-27 04:59
The sample app is checked in, so you can compare (or start from a known-working state, and work incrementally from there), although it looks like you're trying to bundle the resources which the sample app doesn't yet. I'm wondering about your assetsPath though; what is the working directory when you are running the app?

**Comment by Schwusch** [comment] 2018-02-27 12:14
The app is running in sandbox and simply couldn't access files from the outside.

**Closed** 2018-02-27 12:13 UTC
