### ISSUE TITLE
.dll files missing errors during run flutter desktop application on windows 8/8.1

### ISSUE THREAD

**Issue by dheerendrapratap** [google/flutter-desktop-embedding#723] opened 2020-04-23 06:41 UTC
when i run exe file which is generated using Flutter run command. after generating .exe i run it on another system (windows 8). but windows show me error mvsp.dll/vcruntime.dll and other files are missing. 
i need help for solve this issue.

**Doctor Output**
                                                        D:\Microlent\deployments\flutter_desktop_try_new>flutter doctor -v
[√] Flutter (Channel master, v1.16.1, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.16.1 at S:\Android\Flutter
    • Framework revision e6b0f5f238 (5 weeks ago), 2020-03-18 21:56:02 -0400
    • Engine revision 216c420a2c
    • Dart version 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at F:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = S:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.29911.84

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\DHEERENDRA PRATAP S\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18363.720]

• No issues found!

```
```

**Comment by stuartmorgan** [comment] 2020-04-23 14:53
Please read [the Feedback section of the README](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#feedback). This issue is not related to the code in this repository.

Duplicate of https://github.com/flutter/flutter/issues/53167

**Closed by stuartmorgan** 2020-04-23 14:53 UTC
